### ISSUE TITLE
When making a streaming request doesn't update until you reconnect

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/go-horizon#108]
It seems like if I make a streaming request it will give me all the past responses but wont give me new ones until the server drops me and I reconnect. I tried with /transactions

**Comment by nullstyle** [comment]
Confirmed:  I'll look at this right after transaction submission lands

**Comment by nullstyle** [comment]
Fixed with transaction submission PR, which included an overhaul of the streaming subsystem
