### ISSUE TITLE
able to start streaming from now rather than the beginning of time.

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/go-horizon#112]
Might already be possible?

**Comment by nullstyle** [comment]
For this I plan on adding a special value for the `cursor` parameter: `latest`.

I believe this is the appropriate solution to maintain homogeneity between streaming/non-streamed endpoints with regards to what data we show and how we show it.

`cursor=latest` really only makes sense when streaming. If we defaulted to `cursor=latest`, then a non-streaming request would always show an empty set of transactions, which would be weird.  By having it be a parameter we sidestep the issue.

**Comment by jedmccaleb** [comment]
yeah makes sense but can we call the parameter "now"

**Comment by nullstyle** [comment]
sure!
