### ISSUE TITLE
returned links have \u0026 instead of &

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/go-horizon#113]
https://horizon-testnet.stellar.org/payments?limit=1

the "succeeds" link is weird:
/operations?cursor=279172878337\u0026order=desc

**Comment by nullstyle** [comment]
This is a go behaviour: (from the docs)

> String values encode as JSON strings coerced to valid UTF-8, replacing invalid bytes with the Unicode replacement rune. The angle brackets "<" and ">" are escaped to "\u003c" and "\u003e" to keep some browsers from misinterpreting JSON output as HTML. Ampersand "&" is also escaped to "\u0026" for the same reason.

The weirdness should be inconsequential to everything but "I want to copy paste a link from the browser".  Any JSON parser will handle it as expected.

**Comment by nullstyle** [comment]
Sorry, to further explain.  Fixing this would require significant expense without a lot of gain.
