### ISSUE TITLE
Re org docs/resources to describe operations and effects

### ISSUE THREAD

**Issue by dydt** [stellar/go-horizon#116]
The operations resource page (https://github.com/stellar/horizon/blob/master/docs/reference/resources/operation.md) is extremely long, and the effects resource page (https://github.com/stellar/horizon/blob/master/docs/reference/resources/effect.md) does not have a lot of detail.

In addition, I just started a trade.md resource page from an old ticket without being told a Trade is simply an Effect now.  I think it's important to talk about trades in depth, but currently there is no place for the doc I wrote.

I propose that operations should be a folder under resources (/resources/operations/_) and so should effects (/resources/effects/_).

**Comment by nullstyle** [comment]
I'm going to close this for now.  We're working through a redesign of the home page and website in general and it will influence how we organize our docs.
