### ISSUE TITLE
Stream only new objects

### ISSUE THREAD

**Issue by bartekn** [stellar/go-horizon#120]
Streaming endpoints send all the data from the first ledger when requested without `cursor` parameter. However, in most use cases developers don't want this. They only want events that happened since a stream was started. The most common use case will be:
1. Get the most recent page of accounts/transactions/ledgers/operations,
2. Start streaming and display new objects as they appear in horizon.

What do you think?

**Comment by jedmccaleb** [comment]
duplicate: https://github.com/stellar/horizon/issues/112 :)
