### ISSUE TITLE
Error submitting transactions

### ISSUE THREAD

**Issue by bartekn** [stellar/go-horizon#131]
It seems that a new version of go-stellar-base has some problems decoding data. When you try to post a transaction that already exists in a ledger (hence is correct) you get a following error [here](https://github.com/stellar/horizon/blob/2f2678e49f936178e1a948afbf863e4060a2dd82/src/github.com/stellar/horizon/txsub/internal.go#L19):

```
xdr:DecodeInt: EOF while decoding 4 bytes - read: '[]'
```

**Comment by nullstyle** [comment]
Please include an example.  Every transaction I have tried works fine, so most likely something is different in your script.

**Comment by bartekn** [comment]
This one:

```
AAAAAEUeurDvJaIo6w5Yr1cMnfJ7t3PncefG/H34W42JSbHCAAAD6AAAMx0AAAABAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAKNx6I+ez8mt7NmDpeBzNuy6oqIlLGOl2TUuASQ7a09QAAAAAAAAAAAa47WwAAAAAAAAAAYlJscIAAABA8nwc5w3KadakuKBqaBj1l2XA0tyThSgL7mTD9mJiF3QDUXiDrjK05GcG09BQ93M8c+5ILtnKnBpEpd1q1WmDDQ==
```

I was able to successfully submit it to a network using stellar-core directly.

**Comment by nullstyle** [comment]
This is actually a reflection of the need for #132.  Closing in favor of that.
