### ISSUE TITLE
Add non-xdr summary of transaction/operation result codes to a "transaction_failed" error

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/go-horizon#140]
Maybe I'm missing it but I don't see why a transaction fails when I submit it to horizon

**Comment by nullstyle** [comment]
Whoops!  I new I missed something.  

Should I do this now, or after pathfinding? @jedmccaleb

**Comment by jedmccaleb** [comment]
I think it is higher priority but don't want to make you shift gears

**Comment by nullstyle** [comment]
I'll finish up my current task on pathfinding and go add it.

**Comment by nullstyle** [comment]
Fixed in #149
