### ISSUE TITLE
Ability to see what assets an address has issued

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/go-horizon#178]
Want to be able to see what assets an account has issued and the total amount outstanding of each asset.

**Comment by TbLtzk** [comment]
You can reproduce with this pair:
issuer - GC7DJUFVMD5BYXS67MWAAQSJF6UASF47RY2AUCKOR5J2YTWS6ZNIGS6Y
customer - GALYYRH5XCRLVQ3W56PNEZHRV37GY3VFRRFUYU4NNDKOGUAB22OQPUX4
(on the testnet as long as it is not reset)
![client_account](https://cloud.githubusercontent.com/assets/8383712/10802810/1f091e5e-7dbf-11e5-9d26-40e7bc5d4f22.png)

**Comment by nelisky** [comment]
This is a very important feature for DividendRippler, since it is part of the sanity checks done before every transfer and regularly to make sure crypto stored and IOUs issued match. As such I'd appreciate a few pointers and I'll get this done myself if no one more knowledgeable has time to do it soon.

**Comment by jedmccaleb** [comment]
So this solution is a bit complicated since without DB changes there isn't a way to query this info from the stellar-core DB in a scalable way. There are a couple possible solutions 1) write another thing that connects to the stellar-core DB and creates its own table.  2) wait for the horizon importer to be ported to go and then we can add it to horizon.

**Comment by sacarlson** [comment]
I'm not sure this relates but I wrote a action function for multi-sign-server that might be used as a temp solution or ported to horizon that might serve this needed function:

  get_issuer_debt: return totals of all asset debts for this issuer account for each asset issued

```
Values sent:
    issuer: the target issuer account for totaled debts

Values returned
    status: returns success or fail if problems in search detected
    debt: return a hash with a group of key value sets of asset name and debt in each
    issuer: the issuer account address that the search was run with

example input: {"action":"get_issuer_debt", "issuer":"GAMB56CPYXJZUM2QSWXTUFSFIWMNHB6GZBUFJ2YJQJRGW6WH223NRLND"}

example return: {"status":"success", "debt":{"CHP":200110.12,"USD":300}, "issuer","GAMB56CPYXJZUM2QSWXTUFSFIWMNHB6GZBUFJ2YJQJRGW6WH223NRLND"}
```

for details and code: https://github.com/sacarlson/stellar_utility/tree/master/multi-sign-server

**Comment by johansten** [comment]
jed: Is scalability still an issue here? It seems to me that this is still just one SQL query, i.e.
`select assetcode, sum(balance) as total from trustlines where issuer = 'ISSUER' group by assetcode;`

**Comment by nullstyle** [comment]
It's very possible for us to just track this in a database managed by horizon.  I'll look into doing it as I port the importer into go.

**Comment by myrle-krantz** [comment]
This would be useful for keeping issued currency in sync with available real currency.  It would also be very useful for testing.

**Comment by jedmccaleb** [comment]
done here: https://github.com/stellar/go/pull/147
