### ISSUE TITLE
Explain issue labels

### ISSUE THREAD

**Issue by raymens** [stellar/go-horizon#193]
I see several labels named: `in progress`, `in orbit`, `ready`. I like the names, but I'm not sure what they all mean. Maybe explain these in the contribution guide to let outside-developers know what issues they can fix and know what's already being worked on by someone else.

**Comment by jedmccaleb** [comment]
ah right they come from waffle: https://waffle.io/stellar/horizon but I'll add to contribution the guide.

**Comment by jedmccaleb** [comment]
added
