### ISSUE TITLE
cancel all orders

### ISSUE THREAD

**Issue by FredericHeem** [stellar/go-horizon#195]
In order to implement market maker for stellar, it would be more efficient to have an API to cancel all orders for a given account. Right now, we need to get all orders and then cancel them which is not really efficient.

**Comment by nullstyle** [comment]
I don't understand what you mean.  Are you asking for another operation type to be added to stellar-core?  if so, please open up an issue over that way.

In the mean time, I recommend you collect the offers you want to cancel using the offers endpoint, then simply craft a transaction with multiple ModifyOffer operations that cancel each.  It'll let you kill 100 offers at a time.

**Comment by jedmccaleb** [comment]
The other place  besides the core this could be added to would be the js-sdk.

**Comment by nullstyle** [comment]
@jedmccaleb good point.  I would love to see more rich interactions being expressed in the client libraries.
