### ISSUE TITLE
Transaction containing self-payment not visible on the list of transactions

### ISSUE THREAD

**Issue by bartekn** [stellar/go-horizon#196]
Transaction that contains payment with source and destination being the same account is not visible in `/accounts/{address}/transactions`.
- https://horizon.stellar.org/accounts/GB6YPGW5JFMMP2QB2USQ33EUWTXVL4ZT5ITUNCY3YKVWOJPP57CANOF3/transactions
- https://horizon.stellar.org/operations/3201756385251329

**Comment by nullstyle** [comment]
Confirmed.  This occurs since the horizon-importer does not consider the `txfeehistory` table for finding transaction participants.   An account that pays to itself is only effected in one way,  the tx fee, and so it only shows up in the metadata stored in txfeehistory.
