### ISSUE TITLE
Invalid scheme in `_links`

### ISSUE THREAD

**Issue by bartekn** [stellar/go-horizon#208]
`_links` object contains URLs with invalid schema (`http` instead of `https`). It's causing connection reset error in js-stellar-sdk. It seems this problem occurs only on horizon-testnet.

https://horizon-testnet.stellar.org/operations

``` json
{
  "_links": {
    "self": {
      "href": "http://horizon-testnet.stellar.org/operations?order=asc\u0026limit=10\u0026cursor="
    },
    "next": {
      "href": "http://horizon-testnet.stellar.org/operations?order=asc\u0026limit=10\u0026cursor=13563506724865"
    },
    "prev": {
      "href": "http://horizon-testnet.stellar.org/operations?order=desc\u0026limit=10\u0026cursor=55834578945"
    }
  },
```

**Comment by nullstyle** [comment]
Thanks for the heads up.  Apparently something in our proxy config is off for testnet.  Looking into it now.

**Comment by nullstyle** [comment]
Fixed!
