### ISSUE TITLE
Migrate from "address" to "account ID" and "public key" 

### ISSUE THREAD

**Issue by irisli** [stellar/go-horizon#214]
We ( @jessica-collier ) decided on a set of terminology that is more consistent.
`accountID`
`public key`
`secret key`

Also, always use the most specific term.

When referring to the master key of an account (as in the account ID), it is technically both a `account id` and a `public key`. In this situation, we prefer to use the more specific term which is `public key`.

Signer keys should be referred to as `public/secret key` since they are not account ID's.

**Comment by jedmccaleb** [comment]
stellar address refers to things like:  `bob*lobstr.co` now

**Comment by jessica-collier** [comment]
@irisli we decided on secret key, not private key. any reason to change that?

**Comment by irisli** [comment]
Oops. I think you're right @jessica-collier. I made a mistake. Thanks for catching it
