### ISSUE TITLE
[Proposal] Sending User-Agent header by client libraries

### ISSUE THREAD

**Issue by bartekn** [stellar/go-horizon#217]
We may need information about which of SDKs are the most popular in the future. The most standard way to do it is to add `User-Agent` header to every request made by client libraries, for example for js-stellar-base:

```
User-Agent: js-stellar-sdk/0.2.23
```

It may require more work on horizon side but it's not urgent.

**Comment by nullstyle** [comment]
@bartekn I'm not sure how this applies to horizon.  The client libraries would be responsible for sending the header, and our front-end router's access logs is the most appropriate data to use for analytics on user agents, IMO. What did you have in mind?

**Comment by bartekn** [comment]
Cool, we can do it at ELB level then.
