### ISSUE TITLE
add federation resolution?

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/go-horizon#218]
Should we add a /resolve?name=bob*domain.com endpoint that returns the federated response? 
The other option is to just add this to js-stellar-sdk.
If we add it to horizon anyone can use it but it adds another request into the chain. client->horizon->stellar.toml->fed server.
If we add it to js-stellar-sdk we have just client->stellar.toml->fed server. And by far the most likely client for this is from JS.

**Comment by bartekn** [comment]
Federation protocol in js-stellar-sdk: https://github.com/stellar/js-stellar-sdk/pull/49

**Comment by jedmccaleb** [comment]
Closing since we will likely leave this out of horizon for now
