### ISSUE TITLE
Failed to check latest ledgersql: Scan error on column index 0: converting driver.Value type <nil> ("<nil>") to a int32

### ISSUE THREAD

**Issue by masahide7** [stellar/go-horizon#257]
Hello, I am trying to build stellar(core/horizon/wallet) in my server in all-in-one fashion using lxc containers for evaluation. during that, I found an issue in horizon describing in the following:

issue) Horizon keeps error messages once it's started as ``WARN0031 Failed to check latest ledgersql: Scan error on column index 0: converting driver.Value type <nil> ("<nil>") to a int32: invalid syntax pid=30542"

cause) in horizon/src/github.com/stellar/horizon/db/streaming.go, there is a line 

`MaxHistoryLedger = "SELECT MAX(sequence) FROM history_ledgers"`

I don't know about where I can get the correct SQL source for horizon but I used one which I got from https://raw.githubusercontent.com/stellar/horizon/master/src/github.com/stellar/horizon/db/schema/latest.sql 

Please correct me if I'm wrong. Though, using the above SQL, at the very first stage, the table history_ledgers does not contain any records using the above SQL. 

And when I see the program to find out the cause, I found the following piece of code:

```
var latestLedger int32
row := db.QueryRow(MaxHistoryLedger)
err := row.Scan(&latestLedger)
```

As you know, err := row.Scan(&latestLedger) can cause such an error if there are no records in the corresponding table due to a failure in implicit casting of NULL to int32.

That's why the error occurs.

resolution)

I modified it just as follows:

`MaxHistoryLedger = "SELECT MAX(sequence) FROM history_ledgers"`

 to

`MaxHistoryLedger = "SELECT coalesce(MAX(sequence),0) FROM history_ledgers"`

---

Please give me an advice in this approach if there is a more efficient way to handle this kind of error.

Thanks

**Comment by nullstyle** [comment]
@masahide7 Have you setup the horizon-importer project?  At present horizon depends upon it being up, running and accessible.  This specific error occurs when the you are running horizon against an empty database.

This specific error will go away when we've fully removed the need for horizon-importer, which I am currently working.

Thanks for the report!

**Comment by nullstyle** [comment]
This is fixed on master.
