### ISSUE TITLE
Update friendbot query param `addr` to newer terminology `account_id`

### ISSUE THREAD

**Issue by irisli** [stellar/go-horizon#263]
Currently, a friendbot endpoint requires an account id in it's `addr` query param. This param should be `account_id` to be consistent with the rest of horizon's endpoints.

Current: `/friendbot?addr=GAAAAAAAAAAA`
Proposed: `/friendbot?account_id=GAAAAAAAAAAA`

**Comment by nullstyle** [comment]
As we discussed in person, this seems like more churn than is useful for a simple testing facility.
