### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by biggosh** [stellar/go-horizon#282]
Hi.

I'm trying to install horizon and try it connected to testnet.
Stellar seams to work correctly from the log, but when I query horizon the result is always 404. Where am I wrong?

I've tried this:

`curl https://horizon-testnet.stellar.org/accounts/GDDL5IDKHOLS5JPWD3MLLVZQEKVMRRGEAA22F6JJYBQAY5XNWDGBEOW3` : gives not empty result

`curl https://localhost:/accounts/GDDL5IDKHOLS5JPWD3MLLVZQEKVMRRGEAA22F6JJYBQAY5XNWDGBEOW3` : gives empty result

Thanks

**Comment by bartekn** [comment]
Looks like the port number is missing after `:`. Default port is `8000` and you can overwrite it by setting `--port` flag.

**Comment by biggosh** [comment]
Sorry, it's just an error in copying the url, i've used the correct url:

```
 curl http://localhost:8000/accounts/GDDL5IDKHOLS5JPWD3MLLVZQEKVMRRGEAA22F6JJYBQAY5XNWDGBEOW3
{
  "type": "https://stellar.org/horizon-errors/not_found",
  "title": "Resource Missing",
  "status": 404,
  "detail": "The resource at the url requested was not found.  This is usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided.",
  "instance": "stellarnode/QfShhXGFLW-000011"
}
```

**Comment by bartekn** [comment]
You should check: https://www.stellar.org/developers/horizon/learn/admin.html#configuring and https://www.stellar.org/developers/horizon/learn/admin.html#ingesting-stellar-core-data. Also make sure you stellar-core is synced with the network.
