### ISSUE TITLE
500 error when an account as a currency type native in their offer.

### ISSUE THREAD

**Issue by thejollyrogers** [stellar/go-horizon#29]
ERRO[0522] panic: sql: Scan error on column index 2: unsupported driver -> Scan pair: <nil> -> _string  stacktrace=goroutine 43 [running]:
github.com/stellar/go-horizon.func·010()
    /Users/andrewrogers/Code/go/src/github.com/stellar/go-horizon/middleware_recover.go:23 +0xd5
runtime.panic(0x56e4e0, 0xc2083fabe0)
    /usr/local/go/src/pkg/runtime/panic.c:248 +0x18d
github.com/stellar/go-horizon/render.Collection(0xc1b230, 0xc2083b3ea0, 0xc1b3b8, 0xc2083b4c40, 0xc208312d00, 0xc1b490, 0xc2083b4c80, 0x7aa100)
    /Users/andrewrogers/Code/go/src/github.com/stellar/go-horizon/render/main.go:41 +0x17c
github.com/stellar/go-horizon.offerIndexAction(0xc2083ee960, 0xc2083ee870, 0xc1b3b8, 0xc2083b4c40, 0xc208312d00)
    /Users/andrewrogers/Code/go/src/github.com/stellar/go-horizon/actions_offer.go:27 +0x390
github.com/zenazn/goji/web.handlerFuncWrap.ServeHTTPC(0x7aa0f8, 0xc2083ee960, 0xc2083ee870, 0xc1b3b8, 0xc2083b4c40, 0xc208312d00)
    /Users/andrewrogers/Code/go/src/github.com/zenazn/goji/web/handler.go:25 +0x54
github.com/zenazn/goji/web.(_router).route(0xc20802ce38, 0xc208288cc0, 0xc1b3b8, 0xc2083b4c40, 0xc208312d00)
    /Users/andrewrogers/Code/go/src/github.com/zenazn/goji/web/router.go:119 +0x143
github.com/zenazn/goji/web.func·002(0xc1b3b8, 0xc2083b4c40, 0xc208312d00)
    /Users/andrewrogers/Code/go/src/github.com/zenazn/goji/web/middleware.go:88 +0x5f
net/http.HandlerFunc.ServeHTTP(0xc20831b060, 0xc1b3b8, 0xc2083b4c40, 0xc208312d00)
    /usr/local/go/src/pkg/net/http/server.go:1235 +0x40
github.com/PuerkitoBio/throttled.func·003(0xc1b3b8, 0xc2083b4c40, 0xc208312d00)
    /Users/andrewrogers/Code/go/src/github.com/PuerkitoBio/throttled/throttler.go:64 +0x159
net/http.HandlerFunc.ServeHTTP(0xc20831b080, 0xc1b3b8, 0xc2083b4c40, 0xc208312d00)
    /usr/local/go/src/pkg/net/http/server.go:1235 +0x40
github.com/rs/cors.func·001(0xc1b3b8, 0xc2083b4c40, 0xc208312d00)
    /Users/andrewrogers/Code/go/src/github.com/rs/cors/cors.go:160 +0x185
net/http.HandlerFunc.ServeHTTP(0xc20831b0a0, 0xc1b3b8, 0xc2083b4c40, 0xc208312d00)
    /usr/local/go/src/pkg/net/http/server.go:1235 +0x40
github.com/zenazn/goji/web/middleware.func·003(0xc1b3b8, 0xc2083b4c40, 0xc208312d00)
    /Users/andrewrogers/Code/go/src/github.com/zenazn/goji/web/middleware/options.go:70 +0x12b
net/http.HandlerFunc.ServeHTTP(0xc20831b0c0, 0xc1b3b8, 0xc2083b4c40, 0xc208312d00)
    /usr/local/go/src/pkg/net/http/server.go:1235 +0x40
github.com/stellar/go-horizon.func·011(0xc1b3b8, 0xc2083b4c40, 0xc208312d00)
    /Users/andrewrogers/Code/go/src/github.com/stellar/go-horizon/middleware_recover.go:34 +0xf8
net/http.HandlerFunc.ServeHTTP(0xc20831b0e0, 0xc1b3b8, 0xc2083b4c40, 0xc208312d00)
    /usr/local/go/src/pkg/net/http/server.go:1235 +0x40
github.com/stellar/go-horizon.func·012()
    /Users/andrewrogers/Code/go/src/github.com/stellar/go-horizon/middleware_request_metrics.go:19 +0x86
github.com/rcrowley/go-metrics.(*StandardTimer).Time(0xc208081ad0, 0xc2083b3f20)
    /Users/andrewrogers/Code/go/src/github.com/rcrowley/go-metrics/timer.go:212 +0x45
github.com/stellar/go-horizon.func·013(0xc1b3b8, 0xc2083b4b80, 0xc208312d00)
    /Users/andrewrogers/Code/go/src/github.com/stellar/go-horizon/middleware_request_metrics.go:20 +0x1d1
net/http.HandlerFunc.ServeHTTP(0xc20831b100, 0xc1b3b8, 0xc2083b4b80, 0xc208312d00)
    /usr/local/go/src/pkg/net/http/server.go:1235 +0x40
github.com/stellar/go-horizon.func·009(0xc1b150, 0xc208399a40, 0xc208312d00)
    /Users/andrewrogers/Code/go/src/github.com/stellar/go-horizon/middleware_logger.go:26 +0x147
net/http.HandlerFunc.ServeHTTP(0xc20831b120, 0xc1b150, 0xc208399a40, 0xc208312d00)
    /usr/local/go/src/pkg/net/http/server.go:1235 +0x40
github.com/sebest/xff.func·002(0xc1b150, 0xc208399a40, 0xc208312d00)
    /Users/andrewrogers/Code/go/src/github.com/sebest/xff/xff.go:64 +0x86
net/http.HandlerFunc.ServeHTTP(0xc208318f40, 0xc1b150, 0xc208399a40, 0xc208312d00)
    /usr/local/go/src/pkg/net/http/server.go:1235 +0x40
github.com/stellar/go-horizon.func·007(0xc1b150, 0xc208399a40, 0xc208312d00)
    /Users/andrewrogers/Code/go/src/github.com/stellar/go-horizon/middleware_context.go:24 +0x2e8
net/http.HandlerFunc.ServeHTTP(0xc20831b140, 0xc1b150, 0xc208399a40, 0xc208312d00)
    /usr/local/go/src/pkg/net/http/server.go:1235 +0x4

**Comment by nullstyle** [comment]
Fixed
