### ISSUE TITLE
Need a way to determine whether a trustline has been authorized

### ISSUE THREAD

**Issue by Mr0grog** [stellar/go-horizon#298]
It’s pretty straightforward to see what trustlines an account has by checking the objects in the `balances` array (is there any other way?), but those objects don’t seem to indicate whether the trustline is authorized. If the issuer of an asset has the authorization required flag set, someone paying that asset would probably want to know whether the receiving account is authorized to receive that asset before actually sending the payment.

So far as I can tell, there’s no way to determine this through Horizon right now. It’d be great if this info was surfaced in the balance object. Even better if it could indicate simply whether an account is able to receive the asset (e.g. it could be authorized, but not being authorized would be OK, too, when the issuer doesn’t require authorization). Not sure how easy/feasible that is, though.

**Comment by nullstyle** [comment]
Sorry about the delay in responding.

The intention for the balances property is that only authorized trustlines show up.  I notice now that I don't properly filter unauthorized trustlines out... I'll fix that on monday.  This design is in response to the pain we had developing against the ripple API back in the day:  The requirements on interpretting the data correctly was too high and led to all sorts of buggy code on our part.  Instead, we provide data that should be simple to interpret correctly in one case (for example, building a payment client) but may be non-optimal for other cases (for example, showing a comprehensive list of trustlines for an account).

There will be a separate property for pending trustlines at some point.

**Comment by jedmccaleb** [comment]
This is cool but I wonder if we need some way to get the trustlines even if they haven't been authorized? 

I also added something to the horizon docs about this.

**Comment by nullstyle** [comment]
> There will be a separate property for pending trustlines at some point.

The above will work for determining the pending trustlines for a personal account, and I can see us adding either a new effect type (something like "trustline_requested") or a separate endpoint specifically for anchors that lists incoming pending trustlines.

**Comment by Mr0grog** [comment]
> I also added something to the horizon docs about this.

Should the docs have been updated if the code doesn’t do that yet? (Especially if it’s not shipped.)

**Comment by r8d8** [comment]
So, can you please specify how this authorization state should be presented.
If I got it right, here is [request to db](https://github.com/stellar/go/blob/master/services/horizon/internal/db2/core/trustline.go#L41) that returns info for account, and then [API callback](https://github.com/stellar/go/blob/master/services/horizon/internal/actions_account.go#L28) for account info

**Comment by jedmccaleb** [comment]
now tracked here: https://github.com/stellar/go/issues/159
