### ISSUE TITLE
Ledger resource doc is missing some fields

### ISSUE THREAD

**Issue by Mr0grog** [stellar/go-horizon#299]
The [ledger resource doc](https://github.com/stellar/horizon/blob/master/docs/reference/resources/ledger.md) is missing:
- `total_coins` (string)
- `fee_pool` (string)
- `base_fee` (number, stroops)
- `base_reserve` (string, lumens)
- `max_tx_set_size` (number)

@nullstyle I’m happy to do a PR, but I’m not clear on `total_coins` (is this # of lumens in circulation?) and `fee_pool` (sum of all transaction fees since last inflation?). Is `max_tx_set_size` the max number of transactions that will be nominated as described [here](https://www.stellar.org/developers/guides/concepts/fees.html#surge-pricing), or just the max that can be accepted, period? I'm not really sure.

**Comment by nullstyle** [comment]
@Mr0grog:  correct on `total_coins` and `fee_pool`.  Regarding `max_tx_set_size`, I'm not quite sure so @jedmccaleb will have to interject.  My understanding is that `max_tx_set_size` represents the number of transactions that may be nominated per ledger.

**Comment by jedmccaleb** [comment]
a lot of these are described here: https://www.stellar.org/developers/guides/concepts/ledger.html so maybe link to this.  Yes max_tx_set_size is the surge pricing you linked to.
