### ISSUE TITLE
Pathfinding should allow to set source_asset_code

### ISSUE THREAD

**Issue by mmalmi** [stellar/go-horizon#301]
For example, I might want a path payment with destination_asset_type=XLM, sourcing from my EUR assets instead of the XLM I need for transactions.

**Comment by jedmccaleb** [comment]
Right now it should return a path from any source asset you hold (including XLM) to the destination asset. So you can just pick the one using EUR

**Comment by mmalmi** [comment]
Fair enough - then getting the path is just up to #302.
