### ISSUE TITLE
Data returned in effect when issuer sends payment of self issued asset to client asset_code and type transaction is incorrect.

### ISSUE THREAD

**Issue by sacarlson** [stellar/go-horizon#304]
I found what I would consider a bug in horizon return effect data when an issuer sends issues of an asset from itself to a client.  the effect returns the asset_code as "XLM" instead of what was sent in my case "FUNT".  the issuer data is still correct but the asset_code is wrong.  also the effect type transaction is wrong as effect is calling it a trade and the op return is calling it a payment.  so that is also incorrect. (edited)

I am working now on a work around for myself in that I combine the op data and trx data and effect data into a single object that I use for display data.  however being that the effect also returns type of transaction as "trade"  it makes it a bit more difficult to act as I don't know if it's really a trade or a direct issuer payment.

In the example transaction bellow the issuer: GAX4... sent  amount: 11.0,  asset_code: "FUNT"   issuer: GAX4...  To destination addressID: GAVU... 

direct issuer send to client  registered as trade:

effect: valued info
   amount: -11
   asset_code: "XLM"
   asset_issuer: "GAX4..."
   account: "GAX4..."
   type: "trade"
   trans_balance: "8308.99969"

trx: valued info
 create_at:  2016-08-25T12:25:48Z
 id: 5a70e6bc096cec5e044725fae9cffb5e3632bcb8b786eea6377344c919369858

op: valued info
  amount: "11.0000"
  asset_code: "FUNT"
  asset_issuer: GAX4...
  from: "GAX4..."
  source_account: "GAX4.."
  to: "GAVU..."
  type: "payment"

This transaction was done on testnet

**Comment by nullstyle** [comment]
I'm not seeing any trade effects associated with that operation:   https://horizon-testnet.stellar.org/operations/13282680284123137/effects.

Are you sure you don't have a bug in your code?

**Comment by sacarlson** [comment]
From your effects link above I would have to say that the problem must not be in horizon if that's what javascript sdk pulls.  it might be in javascript sdk or more likely in my code some place.  but in any case I have a working work around for my problem so until others find it to be a problem I'm  good with the way it is.  If for any reason some one wants to see the code in question and my solution it can be seen here: https://github.com/sacarlson/sacarlson.github.io/tree/master/my_wallet
