### ISSUE TITLE
Account paging_token incorrect?

### ISSUE THREAD

**Issue by johansten** [stellar/go-horizon#305]
I'm trying to make streaming work in a robust way, to restart at the proper place in case of a lost connection. Using an explicit paging_token instead of 'now' seems the logical solution, but I'm struggling to find my initial starting location -- the paging_token field in my account information gives me '9284761516251754' as a value, but my most recent token should be '13437870337429505'. The account is created in '12611926651572224', so the value given to me in the account information makes absolutely no sense.

**Comment by nullstyle** [comment]
Since this ticket was opened we removed the paging_token from accounts (as part of support for partial history in horizon).
