### ISSUE TITLE
Why isn't horizon using DisableHTMLEscaping?

### ISSUE THREAD

**Issue by mvaneijk** [stellar/go-horizon#317]
It would be nice to have
```
  "_links": {
    "self": {
      "href": "https://horizon-testnet.stellar.org/payments?order=asc&limit=10&cursor="
    },
```

Instead of
```
  "_links": {
    "self": {
      "href": "https://horizon-testnet.stellar.org/payments?order=asc\u0026limit=10\u0026cursor="
    },
```
The former code works when pasting the link in the browser, the latter doesn't.   
However, as mentioned in the golang doc (https://golang.org/pkg/encoding/json/#Marshal) it is possible that some browsers won't show the API at all because it will be interpreted as HTML.

Is Horizon intentionally designed to encode the `&` or was just the default behavior of golang used.

**Comment by nullstyle** [comment]
DisableHTMLEscaping didn't exist when we first wrote horizon:  https://github.com/golang/go/issues/14749
