### ISSUE TITLE
Trades for orderbook returns all trades (instead of filtering just the ones I want)

### ISSUE THREAD

**Issue by irisli** [stellar/go-horizon#318]
Example: https://www.stellar.org/laboratory/#explorer?resource=order_book&endpoint=trades&values=eyJzZWxsaW5nX2Fzc2V0Ijp7InR5cGUiOiJjcmVkaXRfYWxwaGFudW00IiwiY29kZSI6IlVTRCIsImlzc3VlciI6IkdCQU1CT09aRFdaUFZWNTJSQ0xKUVlNUU5YT0JMT1hXTlFBWTJJRjJGUkVWMldMNDZEQkNIM0JFIn0sImJ1eWluZ19hc3NldCI6eyJ0eXBlIjoibmF0aXZlIn19&network=public

I am searching for USD<->native. But it shows me everything else too.

**Comment by irisli** [comment]
The endpoint still returns the data I need (if you sort by descending, you will see a bunch of trades with `USD` issued by my account `GBAMBOOZ`). But it just shows all data available which slows things down.

**Comment by nullstyle** [comment]
I've got a repro and the beginnings of a regression test for this bug... i'll report back with the ETA on a fix.

**Comment by nullstyle** [comment]
There has been a complication in solving this because of the "Rebind" functionality used in sqlx...  it breaks the jsonb operators used by this query.

the appropriate FIXME:  https://github.com/jmoiron/sqlx/blob/master/bind.go#L36

I will need to resolve this underlying issue first.
