### ISSUE TITLE
Unable to retrieve key data value when key contains special characters

### ISSUE THREAD

**Issue by bartekn** [stellar/go-horizon#325]
I created a [test account](https://horizon-testnet.stellar.org/accounts/GA3LIOAX5BFWJWCM2MLTDRALGRQGOO7P2SJMFCBDN5U3Y2XVYMGI3VAT) with the data field with the following name: `test/=&`. It seems, that it's impossible to get the value using `/account/{id}/data/{key}` endpoint. I tried escaping special characters (`test%2F%3D%26`) but it didn't help.

**Comment by nullstyle** [comment]
Diagnosis:  We do not unescape path values returned using the `GetString()` helper
Solution:  dooo eeeet!
