### ISSUE TITLE
Query all offers and/or issuers for a particular asset?

### ISSUE THREAD

**Issue by scott-condie** [stellar/go-horizon#327]
Would it be useful to have a horizon endpoint that lists all of the issuers of a particular asset?  This adds a degree of network discoverability to horizon.  I can know who is participating in the market for BTC (for example).  

Likewise, it might be useful to be able to query all offers for a particular asset.  Something like `StellarServer.offers('BTC',null)` could return all offer/issuer pairs regardless of the issuer.  This would allow easy construction of the orderbook for a particular asset.  It would then be up to the client to determine the level of trust that they have for each issuer.

**Comment by jedmccaleb** [comment]
done here: https://github.com/stellar/go/pull/147
