### ISSUE TITLE
Return timestamps in trades for orderbook

### ISSUE THREAD

**Issue by irisli** [stellar/go-horizon#329]
The trades for orderbook endpoint does not return timestamps or ledger number of the trade. Ideally, it would return both ledger number and timestamp that the trade occurred.

Right now, there is no way to trivially get the data via Horizon. Other stuff works fine though. I have a trading history chart implemented and all I need now is the timestamps.

Example request:
> https://www.stellar.org/laboratory/#explorer?resource=order_book&endpoint=trades&values=eyJzZWxsaW5nX2Fzc2V0Ijp7InR5cGUiOiJjcmVkaXRfYWxwaGFudW00IiwiY29kZSI6IlVTRCIsImlzc3VlciI6IkdCQU1CT09aRFdaUFZWNTJSQ0xKUVlNUU5YT0JMT1hXTlFBWTJJRjJGUkVWMldMNDZEQkNIM0JFIn0sImJ1eWluZ19hc3NldCI6eyJ0eXBlIjoibmF0aXZlIn19&network=public

Thanks!

**Comment by bartekn** [comment]
@nullstyle what would be the solution you'd accept to close this? IMHO, the best way would be to denormalize DB a bit (I explained it here a long time ago: https://github.com/stellar/horizon/issues/89). The quick/easier way would be to: 1) add a link to tx which contains timestamp (or at least operation) or 2) `JOIN` needed table and add timestamp but it may not scale well for larger data.

cc: @jedmccaleb

**Comment by nullstyle** [comment]
@bartekn I was planning on first investigating the feasibility of the `JOIN` solution, then falling back to adding a link at the minimum.  

I haven't thought much about denormalization and maintenance lately, but will take a look at #89 and spin some of that back into my brain.  The effort of denormalizing is IMO too much to justify for this ticket alone, so my preferred route would be if we can solve the problem in the meantime in another way.

**Comment by irisli** [comment]
I think adding a link to the ledger works just fine for now. :+1: For large histories to be useful and performant anyways, clients (or some back end made by the client maker) will want to store the trade history. Having to follow a link isn't that annoying.

**Comment by jedmccaleb** [comment]
hmm I'd much rather have the timestamp here and not have to follow a link.  You really want the time of the trade if you are interested in the trade. If there is a link 90% of the people will have to follow it

**Comment by jedmccaleb** [comment]
#345
