### ISSUE TITLE
Unable to resolve dependencies.

### ISSUE THREAD

**Issue by chainhead** [stellar/go-horizon#333]
Running `gb vendor restore`. It results in a FATAL error message as 'unknown command "vendor"'. When I run the  `gb-vendor` command, it returns a error message as 'it is meant to be run as gb vendor ...'.

How do I resolve dependencies?

**Comment by bartekn** [comment]
From `gb` help:
```
gb supports git style plugins.

A gb plugin is anything in the $PATH with the prefix gb-. In other words
gb-something, becomes gb something.

gb plugins are executed from the parent gb process with the environment
variable, GB_PROJECT_DIR set to the root of the current project.

gb plugins can be executed directly but this is rarely useful, so authors
should attempt to diagnose this by looking for the presence of the
GB_PROJECT_DIR environment key.
```
So it looks like `gb-vendor` is not in your `$PATH`.

**Comment by chainhead** [comment]
It is not in the path; but, I am using full path to invoke `gb-vendor`. It doesn't work that way? I have never worked with Go before.

**Comment by chainhead** [comment]
Setting the `GB_PROJECT_DIR` to the folder for `horizon` seems to be doing the trick ...

**Comment by bartekn** [comment]
Also, you don't have to build the project if you just want to use it. There are binaries to download here: https://github.com/stellar/horizon/releases
