### ISSUE TITLE
Per stellar-core installation?

### ISSUE THREAD

**Issue by chainhead** [stellar/go-horizon#335]
Where exactly does the Horizon server 'sit' in the overall Stellar network (main or test)? 

I know that the Horizon server needs the `STELLAR_CORE_URL` parameter set to a node running Stellar Core. So, are the URLs for Horizon main or test (`https://horizon.stellar.org/` or `https://horizon-testnet.stellar.org/`) referring to one particular node running Stellar Core for main or test? Or, are they URLs for a load balancing system that has a number of Horizon servers each connected to a node running Stellar Core?

**Comment by jedmccaleb** [comment]
Those URLs point to instances of Horizon that SDF runs. You can run your own Horizon. You can also run multiple instances of Horizon and have one URL that load balances between them.

**Comment by chainhead** [comment]
Got it, thanks!
