### ISSUE TITLE
Funding accounts.

### ISSUE THREAD

**Issue by chainhead** [stellar/go-horizon#337]
On the test network, there is the friendly bot that gives out XLM to fund an account. How does one fund an account on the main network or a private network?

On the main network, do I pay an anchor in a fiat currency (say, EUR) who in turn funds my account with EUR or XLM? On a private network, how do I issue XLM (in return for EUR, say) for payments?

**Comment by jedmccaleb** [comment]
On a private network look for the secret key of the root account when the server starts up.  It has all the native asset and you can then do whatever you want with it since you have the secret key. On the live network you can get them from these markets: http://coinmarketcap.com/currencies/stellar/#markets or things like this: https://www.stellar.org/lumens/build/

Also here is a forum for these type of questions:  https://galactictalk.org/

**Comment by nengine** [comment]
@jedmccaleb since native asset like XLM can be issued using secret key of the root account on the private network, I assume secret key of the root account is generated randomly on each private node?

**Comment by jedmccaleb** [comment]
yeah it is generated from the hash of the network passphrase

**Comment by nengine** [comment]
Thanks a lot.  Is it same as "stellar-core --genseed"?

**Comment by willemdejongh** [comment]
I have tried to get the secret key of the root account by setting logging to verbose as described elsewhere, but the secret key of the root account never gets printed. Any other way of obtaining it?

**Comment by jedmccaleb** [comment]
grep for" "Root account seed"  probably only printed when you start the network fresh. it is just sha256(network passphrase)

**Comment by willemdejongh** [comment]
Hi Jed,

Thank you so much for the information. I did find the root account seed.

I have built a private network with 5 stellar core nodes all on Ubuntu Linux, I complied stellar-core from source  and configured them. 
They do communicate with each other, but the state always stays as Joining SCP :

stellar-core -c info
Content-Length: 384
Content-Type: application/json

2017-10-31T09:00:00.144 GBA2J [default INFO] {
   "info" : {
      "build" : "v0.6.3-78-gbb92022",
      "ledger" : {
         "age" : 1509440400,
         "closeTime" : 0,
         "hash" : "e6c40a53c80bf9ad8bef401c1fb3dd8def96f29609bf369fe391ec58c95417e5",
         "num" : 2
      },
      "network" : "TrustPay Network ; October 2017",
      "numPeers" : 4,
      "protocol_version" : 8,
      "state" : "Joining SCP"
   }
}


I am using the following to clean the instances and start them up:

stellar-core --newdb
rm -R /tmp/stellar-core/
stellar-core --newhist local
stellar-core --forcescp
stellar-core

All my instances's stellar-core.cfg files looks like :

NODE_SEED="SBI3CZU7XZEWVXU7OZLW5MMUQAP334JFOPXSLTPOH43IRTEQ2QYXU5RG" # remove this is you are non-validating
NODE_IS_VALIDATOR=true
HTTP_PORT=11626

PUBLIC_HTTP_PORT=true

DATABASE="postgresql://dbname=stellardb user=stellar password=saphira host=127.0.0.1"

#FAILURE_SAFETY is checking whether X nodes are up (exchanging SCP messages)
FAILURE_SAFETY=1

CATCHUP_RECENT=60480

NETWORK_PASSPHRASE="TrustPay Network ; October 2017"

NODE_NAMES=[
 "GDK2SGNAERG53WAZBACCNDA6SNQWOT6WZ3U4JI4ZZJGRCM65DRMZ4UTC  server150",
 "GDTOMH6E2XVRAVR3EZU3LRKQFU25VO4O2FYSAMXTHZQ6EZ2XWTWDRDWS  server81",
 "GARB5Q6ACR35IVICIMR32ASNWK47MNR5YH4GW2HBDETM6HA6SV4SJHRX  server83",
 "GBV3YKU2UEPQRN3JEPVY7HM6OIW2J6UN5REPZF56KYEOIO6UI7ZWKTOL  server224"
]

KNOWN_PEERS=[
"10.0.0.150:11625",
"10.0.0.81:11625",
"10.0.0.83:11625",
"10.0.0.224:11625"
]
[QUORUM_SET]
#THRESHOLD_PERCENT is for agreement so if X percent of my quorum agrees I'm ok with adding this tx to ledger
VALIDATORS=[
"$server150",
"$server81",
"$server83",
"$server224"
]

[HISTORY.local]
get="cp /tmp/stellar-core/history/vs/{0} {1}"
put="cp {0} /tmp/stellar-core/history/vs/{1}"
mkdir="mkdir -p /tmp/stellar-core/history/vs/{0}"


With the correct keys and server names.

Are there any detailed documentation how to do this? Can you maybe assist in where I am going wrong?
Your help will be highly appreciated..

Kind Regards

Willie de Jongh
willie@trustpay.biz <mailto:willie@trustpay.biz>

Trustpay Holding Limited is a company registered in the Republic of Mauritius. Registered number: 125834.

Registered office: Trustpay, Maitland, Suite 510, 5th Floor, Barkly Wharf, Le Caudan Waterfront, Port-Louis, Mauritius, 11307

*****CONFIDENTIALITY NOTICE*****

This message is private and confidential. If you have received this message in error, please notify us and remove it from your system.

**Comment by jedmccaleb** [comment]
Since you don't have that many nodes maybe try setting UNSAFE_QUORUM=true
hard to know without looking at the log. Maybe also try starting with one node and adding others. Adjust the qsets as nodes come on.

**Comment by nengine** [comment]
@willemdejongh I had similar situation and most likely it was causing because other nodes cannot read history archives.  In my case I only had two nodes.  On the first node (node 1) I write history archive similar to your configuration, but for second node, I configure Apache server, so that node 2 can read archive data written from node #1.  Note that I'm not writing history archive on node 2.  

Start node 1 first, and then wait until you see "Synced!". And then start node 2.  You should also see "Synced!"  using a  "stellar-core --c 'info' " command.  

This may not be the best config for production, but works for testing in my case.  

node 1
```
[HISTORY.local] 
get="cp /tmp/stellar-core/history/vs/{0} {1}" 
put="cp {0} /tmp/stellar-core/history/vs/{1}" 
mkdir="mkdir -p /tmp/stellar-core/history/vs/{0}"
```

node 2
```
[HISTORY.h1]
get="curl -sf http://trustpay.biz/dev/core-testnet/core_testnet_001/{0} -o {1}"
```

**Comment by willemdejongh** [comment]
Hi Jed,

Thank you very much for the advice, will try it out and let you know.

Kind Regards

Willie de Jongh
willie@trustpay.biz <mailto:willie@trustpay.biz>

Trustpay Holding Limited is a company registered in the Republic of Mauritius. Registered number: 125834.

Registered office: Trustpay, Maitland, Suite 510, 5th Floor, Barkly Wharf, Le Caudan Waterfront, Port-Louis, Mauritius, 11307

*****CONFIDENTIALITY NOTICE*****

This message is private and confidential. If you have received this message in error, please notify us and remove it from your system.

**Comment by willemdejongh** [comment]
Thank you very much for this response. 
Will try it out and let you know.

Willie de Jongh
willie@trustpay.biz <mailto:willie@trustpay.biz>

Trustpay Holding Limited is a company registered in the Republic of Mauritius. Registered number: 125834.

Registered office: Trustpay, Maitland, Suite 510, 5th Floor, Barkly Wharf, Le Caudan Waterfront, Port-Louis, Mauritius, 11307

*****CONFIDENTIALITY NOTICE*****

This message is private and confidential. If you have received this message in error, please notify us and remove it from your system.

**Comment by willemdejongh** [comment]
Hi ,
This was the issue and my nodes are now syncing.
Thank you so much!

Kind Regards

Willie de Jongh
willie@trustpay.biz <mailto:willie@trustpay.biz>

Trustpay Holding Limited is a company registered in the Republic of Mauritius. Registered number: 125834.

Registered office: Trustpay, Maitland, Suite 510, 5th Floor, Barkly Wharf, Le Caudan Waterfront, Port-Louis, Mauritius, 11307

*****CONFIDENTIALITY NOTICE*****

This message is private and confidential. If you have received this message in error, please notify us and remove it from your system.

**Comment by swetakedia** [comment]
I am trying to set up a private network of 5 nodes - all 5 nodes are in same AWS instance. Just changed the port http and peer port no. in stellar-core.cfg file.

When I start node 1 & 2 it gets synced however node3, 4 & 5 are not getting synced. I am getting below as status:

**Node 3:**

"status" : [
"Catching up: Awaiting 1/1 prerequisites of: get-history-archive-state",
"Proposing herder configuration upgrades: [PROTOCOL_VERSION=9, MAX_TX_SET_SIZE=50]; network values for LCL are: PROTOCOL_VERSION=0, BASE_FEE=100, MAX_TX_SET_SIZE=100, BASE_RESERVE=100000000"

**Node 4:**

"status" : [
"Proposing herder configuration upgrades: [PROTOCOL_VERSION=9, MAX_TX_SET_SIZE=50]; network values for LCL are: PROTOCOL_VERSION=0, BASE_FEE=100, MAX_TX_SET_SIZE=100, BASE_RESERVE=100000000"

**Node 5:**
"status" : [
"Proposing herder configuration upgrades: [PROTOCOL_VERSION=9, MAX_TX_SET_SIZE=50]; network values for LCL are: PROTOCOL_VERSION=0, BASE_FEE=100, MAX_TX_SET_SIZE=100, BASE_RESERVE=100000000"
]

How much time ideally it takes for nodes to be in sync?

Am I missing something?

History in stellar-core.cfg is set as given below:

**Node1:**
[HISTORY.vs]
get="cp /tmp/node1/stellar-core/history/vs/{0} {1}"
put="cp {0} /tmp/node1/stellar-core/history/vs/{1}"
mkdir="mkdir -p /tmp/node1/stellar-core/history/vs/{0}"

**Node 2:**

[HISTORY.vs]
get="cp /tmp/node2/stellar-core/history/vs/{0} {1}"
put="cp {0} /tmp/node2/stellar-core/history/vs/{1}"
mkdir="mkdir -p /tmp/node2/stellar-core/history/vs/{0}"

**Node 3:**

[HISTORY.vs]
get="cp /tmp/node3/stellar-core/history/vs/{0} {1}"
put="cp {0} /tmp/node3/stellar-core/history/vs/{1}"
mkdir="mkdir -p /tmp/node3/stellar-core/history/vs/{0}"

**Node 4:**

[HISTORY.vs]
get="cp /tmp/node4/stellar-core/history/vs/{0} {1}"
put="cp {0} /tmp/node4/stellar-core/history/vs/{1}"
mkdir="mkdir -p /tmp/node4/stellar-core/history/vs/{0}"
