### ISSUE TITLE
is `horizon db reingest` broken?

### ISSUE THREAD

**Issue by mvaneijk** [stellar/go-horizon#341]
Hi, I tried to generate new test scenarios using the build_test_scenarios script. But at the `db reingest` step, I only get a summer that 0 entries are ingested:
```
`INFO[0000] reingest: complete                            count=0 means=load: 0 clear: 0 ingest: 0 pid=6504 rate=0`
```
I verified that the core database has indeed data and when I just start horizon it also ingests the data.

I dived in a little deeper and found that the ledger state was zero when running the `db reingest` command. So then I tried with adding
```
initApp(cmd, args)
app.UpdateLedgerState()
```
to cmd/horizon/db.go:101 and then the data gets ingested. Is this a correct solution, or should the app been started somewhere else in the process?

**Comment by nullstyle** [comment]
It works for me.  Could you please try again and report back?
