### ISSUE TITLE
time stamps on trades

### ISSUE THREAD

**Issue by antb123** [stellar/go-horizon#344]
I need to get daily trade volumes from horizon

https://horizon.stellar.org/order_book/trades?selling_asset_type=native&buying_asset_type=credit_alphanum4&buying_asset_code=EUR&buying_asset_issuer=GDI73WJ4SX7LOG3XZDJC3KCK6ED6E5NBYK2JUBQSPBCNNWEG3ZN7T75U

Does not provide time stamps on trades. This makes it hard to get daily volumes and high low close data.

**Comment by jedmccaleb** [comment]
#345
