### ISSUE TITLE
Exchange related Questions/Problems/Suggestions 

### ISSUE THREAD

**Issue by istrau2** [stellar/go-horizon#349]
Over the last week I have attempted to build the front end for a (primitive) distributed exchange using horizon as its back end. I have run into some problems that I though I could bring up here (as they might lead to solutions or I could possibly discover some things that I did not realize about horizon).

1) Discoverability of assets is very limited. By this, I mean that there is no way to ask horizon "I want to trade BTC, which issuers have issued BTC?" In fact, there is no way to query for
a. assets by issuer
b. assets by code (i.e. all assets regardless of issuer that have this code)
c. issuers by asset code 
d. implement an autocomplete on an asset code or issuer.
Basically what I tried to implement was an autocomplete that completed on an available code (i.e. user types "B" and the autocomplete offers: "BTC", "mBTC" and "THB". Then, after user chooses a code, a second autocomplete offers possible issuers. Is the expectation that secondary applications will record this kind of information to offer users (i.e. should my app cache asset/issuer combos in its own db for querying) or is there some way to get this kind of info from Horizon?

2) Ticker/Price info seems to be non-existent. I mean, it seems that my only option for building any kind of graph is to just pull the actual trades from horizon and build a graph from that (unless I want to store ticker info in my own db). However, I was surprised that when I pulled trade info there was no date information supplied with the trade. I would think that the time of the trade is something that already exists in stellar (as transactions seem to have a time associated with them and a trade is just a special kind of transaction). 

I would appreciate any thoughts or suggestions regarding these issues. Thanks.

**Comment by istrau2** [comment]
So, I have started looking into caching some of this info myself. I think assets are probably very straightforward to do. Price/Ticker info might be trickier but still doable. However, it would be great if:

There could be a "All Trades" endpoint (just like "All Effects" or "All Payments etc.) that one could stream from and if the trade could include the created_at timestamp.

**Comment by istrau2** [comment]
Thinking about it more, I guess I could just stream from "All Effects" and filter on the effect type. I guess what is really throwing me through a loop is the fact that I have to traverse from effect -> operation -> transaction to get the timestamp. This basically means that I have to make 2 extra requests (one for the opreration and then another following it for the transaction) to obtain an effect's timestamp. This is kind of problematic given horizon's request rate limit.

**Comment by jedmccaleb** [comment]
Hi istrau2 
1) I don't think this makes sense to do through horizon. You need some external way to determine if you want to hold a particular asset. Just because some random person is offering BTC on stellar you probably don't want to trade it unless you know who that person is.  For caching different assets, I would do something like what stellarterm.com is doing.

2) Yes timestamps were added to trades. Maybe our public horizon hasn't been updated yet. Checking now...

I think an "All trades" endpoint is feasible. I'll make a separate issue for that.

Also as far as rate limiting, you can always run your own horizon.

**Comment by istrau2** [comment]
Hi @jedmccaleb 

Thanks  for the response.

1) Yes, that makes sense. I was already thinking about caching them.
2) Do you mean that timestamps were added to the orderbook/trades endpoint or were they also added to the effects endpoint?

**Comment by jedmccaleb** [comment]
timestamps were just added for trades. It is on our public horizon instance now.

**Comment by istrau2** [comment]
@jedmccaleb Thanks for the responsiveness. I really appreciate it. Would it be possible to add timestamps to the effects too? Its just that I don't think that building graphs from the lower level trade data is going to scale very well. I was thinking that I would stream the effect data, filter on effect type (of type "trade") and store precalculated ticker data in a db.

**Comment by jedmccaleb** [comment]
What are you trying to do? You might just want to look in the DB directly?

**Comment by istrau2** [comment]
@jedmccaleb I am trying to construct candlestick style graphs of a specific exchange (i.e. asset combination). Of course, I could just pull the trades for an orderbook and use those to construct a graph. However, I am afraid that that approach wont scale. I mean, if a user wants to see a graph of the last year, I would have to pull all the trades for a year.

I was thinking I could precalculate ticker values (think high/low/open/close/volume stats) for various time intervals and pull those instead.

To do that I was going to stream the effect data and calculate the tickers.

How do I look in the db directly?

**Comment by jedmccaleb** [comment]
Yeah I think you want to have a process that either looks in the DB directly or does this streaming trade thing from horizon and saves the daily HLOCV stats in the DB. Then you can build your graphs by pulling that data rather than recomputing it all the time. 
If you run stellar-core it saves all of this to a postgres database. But if that is a hassle for you then just calculate like I suggest above from horizon and stick it in your own DB.

**Comment by istrau2** [comment]
@jedmccaleb Sorry, when you say "stellar-core saves all this to a postgres db" what do you mean by "this"? Is it saving the HLOCV stats in the db or is it saving the events and trades to the db?

I was planning on doing the streaming thing but the problem is that I have to stream events (since there is no "All Trades" endpoint). However, events don't have any timestamp. So, every time there is a trade event I have to go and get the trade by cursor to obtain the timestamp. I would think it would be useful to have the timestamps on the events as well as the trades (isn't a trade just a special kind of event?).

**Comment by jedmccaleb** [comment]
stellar-core saves all the event and trade data to the DB.

ok we will probably add the "all trades" endpoint. In the meantime maybe you can just look a a few pre-specified orderbooks?

**Comment by istrau2** [comment]
@jedmccaleb Thanks. Yes, its ok, I have a solution in the meantime.
