### ISSUE TITLE
Horizon timeouts when submitting tx in dev environment

### ISSUE THREAD

**Issue by Akuukis** [stellar/go-horizon#354]
Hello,

I have deployed my own stellar network and horizon in various dockers on the same machine. 3 stellar-cores are making consensus once per 5 seconds, time to time copying history to S3 bucket, horizon can ingest ledgers and query anything I have asked. But, when I submit transaction (either via sdk or curl) to horizon, it freezes and timeouts in 1 minute. Here are horizon logs:
```
time="2017-03-28T14:49:34Z" level=info msg="Starting request" host="10.0.167.200:8000" ip="10.0.162.115:44012" method=POST path="/transactions?tx=<myTxBlob>" pid=64 req="ip-10-0-167-200/L4TntQL2DQ-000198"
time="2017-03-28T14:50:34Z" level=info msg="Finished request" bytes=237 duration=1m0.07596093s pid=64 req="ip-10-0-167-200/L4TntQL2DQ-000198" status=504
```
Transaction does get submitted. It can be seen by both queering the same horizon shortly after, or listening to /transactions stream, or seen in ledger logs:
```
...
2017-03-28T14:49:30.758 GBB2F [Ledger INFO ] Got consensus: [seq=458, prev=f4aa00, tx_count=0, sv: [  txH: 3a9a97, ct: 1490712569, upgrades: [ ] ]]
2017-03-28T14:49:34.761 GBB2F [Ledger INFO ] Got consensus: [seq=459, prev=be1482, tx_count=1, sv: [  txH: 94105a, ct: 1490712574, upgrades: [ ] ]]
2017-03-28T14:49:38.739 GBB2F [Ledger INFO ] Got consensus: [seq=460, prev=098b19, tx_count=0, sv: [  txH: b0055a, ct: 1490712578, upgrades: [ ] ]]
...
```
I don't know what else to debug, everything else seems working. What could cause this? Where should I look further?

**Comment by bartekn** [comment]
Please add your `tx` to the issue.

**Comment by Akuukis** [comment]
I tried with different transactions and network keys, but problem persists. I redo everything on a fresh AWS instance with following scripts but with no luck.

Here's test

```js
const NETWORK = "My Network ; March 2017";
const SECRET = 'SDBFUXNS3JNXIMBW5MMPJVZGMOE6FFT2Y34URPOEABAG5NN5LG4SLUIU';

var StellarSdk = require('stellar-sdk');
var horizon = new StellarSdk.Server('http://10.0.167.90:8000', {allowHttp: true});
StellarSdk.Network.use(new StellarSdk.Network(NETWORK));

var kp = StellarSdk.Keypair.fromSecret(SECRET);

horizon.loadAccount(kp.publicKey())
    .then((account) => {
        console.log(account._baseAccount.sequence)
        const te = new StellarSdk.TransactionBuilder(account)
            .addOperation(StellarSdk.Operation.manageData({
                source: kp.publicKey(),
                name: 'name',
                value: 'value',
            }))
            .build();
        te.sign(kp);
        return horizon.submitTransaction(te);
    })
    .then(res => console.log('Result: ', res))
    .catch(err => console.log('Error: ', err))  // This will output horizon's timeout error in 20 secods
    .then(()=>horizon.loadAccount(kp.publicKey()))
    .then(account=>console.log(account._baseAccount.sequence))  // This will ouput incremented sequence, because tx was exececuted.
```

Horizon was executed like this ...
```sh
docker run --name psql80_0 -e POSTGRES_USER=horizon -e POSTGRES_PASSWORD=mysecretpassword -p8040:5432 -d postgres
docker run --net host \
  -e DATABASE_URL='postgres://horizon:mysecretpassword@localhost:8040?sslmode=disable' \
  -e STELLAR_CORE_DATABASE_URL='postgres://horizon:myreadonlyhorizonpassword@localhost:8041/stellar?sslmode=disable' \
  -e STELLAR_CORE_URL='http://localhost:8001' \
  -e PORT=8000 \
  --name hrzn80_0 -d stellar-horizon
```

... where its image was built with this dockerfile

```docker
// Dockerfile
FROM golang
RUN apt-get update
RUN apt-get install -y postgresql-client
RUN go get github.com/constabulary/gb/...
RUN git clone https://github.com/stellar/horizon.git
RUN cd horizon; gb vendor restore
RUN cd horizon; gb build
ENV PATH horizon/bin/:$PATH
COPY start-horizon.sh horizon/bin/start-horizon.sh
ENV INGEST="true"
ENTRYPOINT ["start-horizon.sh"]
CMD [""]
```

```sh
#!/bin/bash
# start-horizon.sh

while ! psql $DATABASE_URL -c 'select 1' >/dev/null 2>&1;
do
  echo 'Waiting for postgres to be available...'
  sleep 1
done

if [ ! -e "horizon-initiated" ]
then
  echo "Initializing horizon..."
  horizon db init
  touch "horizon-initiated"
fi
horizon serve
```

**Comment by Akuukis** [comment]
And here is how stellar-cores are started (mostly taken from [docker-stellar-core](https://github.com/stellar/docker-stellar-core))
```sh
$AWS_S3_BUCKET="s3://stellar-core-history-manual/"
$NETWORK_PASSPHRASE="My Network ; March 2017"

echo "
POSTGRES_PASSWORD=mysecretpassword
HORIZON_PASSWORD=myreadonlyhorizonpassword

node1_POSTGRES_PORT=8041
node1_PEER_PORT=8071
node1_HTTP_PORT=8001
node1_NODE_SEED=SAJEJWKJAOELT2TJPTNLZXXSC3QXHKXDZD6NZLM3B6VQ7G22DQH5TC6C

node2_POSTGRES_PORT=8042
node2_PEER_PORT=8072
node2_HTTP_PORT=8002
node2_NODE_SEED=SACTBO4KQ3LYYRRKBST3ZCO24FYRDP2CYN3W5IPP2OTC3NUIKFGZSRRY

node3_POSTGRES_PORT=8043
node3_PEER_PORT=8073
node3_HTTP_PORT=8003
node3_NODE_SEED=SCVXYFYE6BQYZD4O6J5ULJXRZYXLMKMXZEI3O3HGTQEB43UOY4XUZV3L

PREFERRED_PEERS=[\
\"127.0.0.1:8071\", \
\"127.0.0.1:8072\", \
\"127.0.0.1:8073\"]

THRESHOLD_PERCENT=51
NODE_IS_VALIDATOR=true
UNSAFE_QUORUM=true
FAILURE_SAFETY=0

VALIDATORS=[\
\"GBB2FMDSJY2VMKKB4QRAXU32OEYV5WPW4CRXB3NQSSD4YENKRMGAC7NB\", \
\"GB4FD5MNQ73WYA47YM2PP443ZE2KUBUI2I36LZAECGZ37ABLUN257GSI\", \
\"GACI4DOR3ILATD6CAPNDAAWVFNCOB3YRQ7BXJ3R7D5K7ICEZOYS26QUN\"]

HISTORY_GET=aws s3 cp $AWS_S3_BUCKET%s/{0} {1}
HISTORY_PUT=aws s3 cp {0} $AWS_S3_BUCKET%s/{1}
HISTORY_RESET=aws s3 rm --recursive $AWS_S3_BUCKET%s

HISTORY_PEERS=[\"node1\", \"node2\", \"node3\"]

NETWORK_PASSPHRASE=$NETWORK_PASSPHRASE\
" > local.env

run () {
  docker run --name psql80_\$1   --env-file local.env -p804\$1:5432 -d stellar/stellar-core-state
  docker run --name node80_\$1 --env-file local.env --net host -v ~/.aws:/root/.aws --volumes-from psql80_\$1 -d stellar/stellar-core /start node\$1 \$2
}
for N in 1 2; do run $N "fresh forcescp"         ; done
for N in 3  ; do run $N "fresh catchupcomplete " ; done
```

**Comment by bartekn** [comment]
I have some problems building your Dockerfile, not sure why it gets stuck downloading horizon dependencies. Before we continue I have some questions:
1. Have you considered using: https://github.com/stellar/docker-stellar-core-horizon ? You should be able to configure it to use other network passphrase.
2. I highly recommend you to use `docker-compose`. You just need to prepare one simple YML file and it will start all the containers using a single command: `docker-compose up`.
3. I think it can be connected to https://github.com/stellar/horizon/issues/292. It can happen when there is no consensus in the network. You have 3 nodes in your network are you 100% sure they can talk to each other and reach consensus? Maybe your horizon is connected to a node that is out of sync?

**Comment by Akuukis** [comment]
It is wierd, for me it always downloaded them, but built quite long, several minutes. Are you using ubuntu instance? So, on your questions...

1. Yes. I started adapting that docker but struggled alot, therefore changed over to 3 stellar-core repo and added horizon to it myself. Today I took a fresh look at it, here are the reasons:
    1. It runs only 1 stellar-core, but I need 3 for demostration purposes. So 3 stellar-core repo looked like a better staring point, because all the peers are configured and ports parameterized.
    2. I didn't found a way to give it network passphrase, but today I rechecked scripts and it looks quite easy to do.
    3. I am using private aws storage, so history get/put scripts using aws instead of curl looked a better starting point.
2. Thanks!
3. In stellar-core logs I can see "Got consensus" and "Closed ledger" once every 5 seconds, so I think its not related. Also the same horizon is able to query the transaction 5 seconds later.

**Comment by Akuukis** [comment]
I re-factored my code to use docker-composer but it doesn't help - horizon still timeouts.

**Comment by Akuukis** [comment]
If I do above mentioned scripts but kill docker horizon at the very beginning, deploy horizon on a AWS instance without docker and point it to my docker stellar-cores, it works and doesn't timeout. Weird...

**Comment by Akuukis** [comment]
I found the trick - horizon have to be started only after stellar-cores reach first (or second) consensus. Here is upgraded `start-horizon.sh` that works together with other above mentioned scripts:

```
#!/bin/bash

while ! psql $DATABASE_URL -c 'select 1' >/dev/null 2>&1;
do
  echo "Waiting for horizon postgres to be available..."
  sleep 1
done

while ! psql $STELLAR_CORE_DATABASE_URL -c 'select 1' >/dev/null 2>&1;
do
  echo "Waiting for stellar postgres to be available..."
  sleep 1
done

while ! curl -sv localhost:8001/info 2>&1 | egrep '"num" : [2-9]' >/dev/null 2>&1;
do
  echo 'Waiting for stellar-cores to reach 2nd consensus...'
  sleep 1
done

if [ ! -e "horizon-initiated" ]
then
  echo "Initializing horizon..."
  horizon db init
  touch "horizon-initiated"
fi
horizon serve
```
