### ISSUE TITLE
your horizon server is stuck at 10006402

### ISSUE THREAD

**Issue by btcid** [stellar/go-horizon#356]
horizon and https://stellarchain.io/ are stuck from 3 hours ago

> #curl "https://horizon.stellar.org/ledgers?order=desc"
> {
>   "_links": {
>     "self": {
>       "href": "https://horizon.stellar.org/ledgers?order=desc\u0026limit=10\u0026cursor="
>     },
>     "next": {
>       "href": "https://horizon.stellar.org/ledgers?order=desc\u0026limit=10\u0026cursor=42977130685923328"
>     },
>     "prev": {
>       "href": "https://horizon.stellar.org/ledgers?order=asc\u0026limit=10\u0026cursor=42977169340628992"
>     }
>   },
>   "_embedded": {
>     "records": [
>       {
>         "_links": {
>           "self": {
>             "href": "https://horizon.stellar.org/ledgers/10006402"
>           },
>           "transactions": {
>             "href": "https://horizon.stellar.org/ledgers/10006402/transactions{?cursor,limit,order}",
>             "templated": true
>           },
>           "operations": {
>             "href": "https://horizon.stellar.org/ledgers/10006402/operations{?cursor,limit,order}",
>             "templated": true
>           },
>           "payments": {
>             "href": "https://horizon.stellar.org/ledgers/10006402/payments{?cursor,limit,order}",
>             "templated": true
>           },
>           "effects": {
>             "href": "https://horizon.stellar.org/ledgers/10006402/effects{?cursor,limit,order}",
>             "templated": true
>           }
>         },
>         "id": "4a4d4494a12db45dc1e1dd194ebad47d30910dddb79ce757d204a1ba66f6102a",
>         "paging_token": "42977169340628992",
>         "hash": "4a4d4494a12db45dc1e1dd194ebad47d30910dddb79ce757d204a1ba66f6102a",
>         "prev_hash": "6083b4feed04346f0af4a204bd9d1812104f0c321060dbf2bcbcd7568fdfbeb7",
>         "sequence": 10006402,
>         "transaction_count": 0,
>         "operation_count": 0,
>         "closed_at": "2017-04-07T00:53:39Z",
>         "total_coins": "102783521117.8548825",
>         "fee_pool": "646213.1674608",
>         "base_fee": 100,
>         "base_reserve": "10.0000000",
>         "max_tx_set_size": 50,
>         "protocol_version": 4
>       }

**Comment by jedmccaleb** [comment]
Sorry this is resolved now
