### ISSUE TITLE
Internal server error occurred, transaction failed, lumens never transferred

### ISSUE THREAD

**Issue by pericazivkovic** [stellar/go-horizon#357]
While using account viewer, I have transferred 15000 lumens to another user. Got a message about server error during the transaction, lumens are gone from my account and never arrived on target address.

Related files attached.

Can I get my lumens back or are they gone for good?

[42676817982656513.txt](https://github.com/stellar/horizon/files/907246/42676817982656513.txt)
[effects-2.txt](https://github.com/stellar/horizon/files/907247/effects-2.txt)

**Comment by bartekn** [comment]
How can you tell that lumens didn't arrive on `GA5X...`? Looking at this operation's [effects](https://horizon.stellar.org/operations/42676817982656513/effects) I can see both `account_debited` and `account_credited` effects. The operation is also in the list of receiver account [operations list](https://horizon.stellar.org/accounts/GA5XIGA5C7QTPTWXQHY6MCJRMTRZDOSHR6EFIBNDQTCQHG262N4GGKTM/operations?limit=1&order=desc&cursor=42677384918339585).

**Comment by pericazivkovic** [comment]
Well receiver is a kraken address that never received this amount (lumens are zero like they were before).

**Comment by bartekn** [comment]
You haven't added memo to your transaction so Kraken doesn't know which account to credit. You need to contact their support.

**Comment by pericazivkovic** [comment]
Thanks for a quick response, will try that
