### ISSUE TITLE
Opening any endpoint in Firefox starts a download

### ISSUE THREAD

**Issue by bartekn** [stellar/go-horizon#358]
https://horizon.stellar.org
Firefox 52.0.2

![screen shot 2017-04-11 at 20 37 27](https://cloud.githubusercontent.com/assets/464938/24924890/b98a1378-1ef6-11e7-9945-62b27e16174c.png)

I think it's because the mime type is `application/hal+json` which is not a standard `application/json`. I think it should be possible to quickly check the horizon response in Firefox.

**Comment by raymens** [comment]
The same goes for Edge, it's the reason I use Opera to browse through horizon. But I'm in favor of keeping it `application/hal+json`.

**Comment by nullstyle** [comment]
I'm not willing to compromise on our `Content-Type`, but I am willing to add a `Content-Disposition` header to encourage browsers to do the right thing.  In my test branch, however, firefox doesn't care and continues to ask if you should download the file.  No clue about Edge, I don't have access to it at present.

The internet recommends firefox users install https://github.com/bhollis/jsonview
