### ISSUE TITLE
Transaction failed - Can not send Lumens

### ISSUE THREAD

**Issue by pvtrien88** [stellar/go-horizon#360]
{
  "type": "https://stellar.org/horizon-errors/server_error",
  "title": "Internal Server Error",
  "status": 500,
  "detail": "An error occurred while processing this request.  This is usually due to a bug within the server software.  Trying this request again may succeed if the bug is transient, otherwise please report this issue to the issue tracker at: https://github.com/stellar/horizon/issues. Please include this response in your issue.",
  "instance": "horizon-live-001/xvGlSNvhW5-14577955"
}

**Comment by bartekn** [comment]
Should work now.
