### ISSUE TITLE
Unable to send Lumens

### ISSUE THREAD

**Issue by PikiPoki** [stellar/go-horizon#362]
{
  "type": "https://stellar.org/horizon-errors/server_error",
  "title": "Internal Server Error",
  "status": 500,
  "detail": "An error occurred while processing this request.  This is usually due to a bug within the server software.  Trying this request again may succeed if the bug is transient, otherwise please report this issue to the issue tracker at: https://github.com/stellar/horizon/issues. Please include this response in your issue.",
  "instance": "horizon-live-002/WbPeIf66nB-25841297"
}

**Comment by bartekn** [comment]
Seems to be working again.
