### ISSUE TITLE
Internal server error when limit exceeds 200 

### ISSUE THREAD

**Issue by chatch** [stellar/go-horizon#365]
The server returns 500 whenever the limit parameter exceeds 200. 

For example:

curl  "https://horizon-testnet.stellar.org/transactions?limit=201&order=desc" gives:

```
{
  "type": "https://stellar.org/horizon-errors/server_error",
  "title": "Internal Server Error",
  "status": 500,
  "detail": "An error occurred while processing this request.  This is usually due to a bug within the server software.  Trying this request again may succeed if the bug is transient, otherwise please report this issue to the issue tracker at: https://github.com/stellar/horizon/issues. Please include this response in your issue.",
  "instance": "horizon-testnet-001/TMLBZMyGsp-7814127"
}
```

Ideally it would return a 400 bad request with the reason in the detail field.

**Comment by nullstyle** [comment]
Diagnosis:  `db2.NewPageQuery` returns an error when a request for a limit over will return `ErrInvalidLimit`.  `ErrInvalidLimit` is not convertible to a `Problem` response.

Solution:  register `ErrInvalidLimit` with the `problem` package using `RegisterError`, include regression test.

**Comment by nullstyle** [comment]
Thanks for the heads up @chatch, I'll get this fixed soon.
