### ISSUE TITLE
504 (timeout) when submitting a transaction to horizon

### ISSUE THREAD

**Issue by istrau2** [stellar/go-horizon#369]
Steps to reproduce:

1. Create an EC2 instance in AWS
2. Expose ports 11626 and 80 in the security group to all ips
3. Install docker on the instance
4. Run the following command to start up a persistent pubnet node:
```
docker run -it -p "80:8000" -p "5432:5432" -p "11626:11626" -v "/home/ec2-user/stellar-volume:/opt/stellar" --name stellar stellar/quickstart --pubnet
```
5. Submit a transaction to your horizon instance

Observation:
The transaction is actually submitted to the network, however, the horizon instance returns 504.

**Comment by bartekn** [comment]
Can you also share AMI ID and command you used to install docker? I want to reproduce it so I need as much information as possible about your instance.

**Comment by istrau2** [comment]
@bartekn 
Thanks a lot for the help. I very much appreciate it. This is how I set up the instance:
1) Use Amazon Linux AMI 2017.03.1 (HVM), SSD Volume Type - ami-a4c7edb2 (the first AMI choice)
2) I have tried with several instance sizes (I don't think size matters)
3) ssh into the instance
4) sudo yum update -y
5) sudo yum install -y docker
6) sudo service docker start
7) sudo usermod -a -G docker ec2-user
8) exit the shell and ssh back in
9) docker info (to confirm that docker was installed correctly)

**Comment by nullstyle** [comment]
A timeout when submitting a transaction to horizon where the transaction does actually get committed to the ledger is usually indicative of stellar-core not properly following the ledger's progress.  

I imagine the issue is similar to, if not the same as https://github.com/stellar/horizon/issues/354

**Comment by nullstyle** [comment]
It seems to me like this is an issue with the `stellar/quickstart` image.

**Comment by istrau2** [comment]
@bartekn Looking at #354, I guess the image is not waiting for stellar-core consensus before starting Horizon (which is causing Horizon to time out).

**Comment by istrau2** [comment]
@bartekn @nullstyle Any progress on this? I would really like to get lupoex.com off of sdf's horizon instance.

**Comment by nullstyle** [comment]
@istrau2 I'm going to be rolling out a new version of the quickstart image today or tomorrow that contains a new build of stellar-core that might help you.

**Comment by nullstyle** [comment]
I'm going to close this now.  We've uploaded a new quickstart image and it should be able to sync more easily with the network.

**Comment by istrau2** [comment]
@nullstyle @bartekn This issue is still plaguing me (I am on the very latest of the stellar quickstart docker image).

Just to throw a wrench into the mix, it seems that when I put horizon behind a load balancer and enable session stickyness, I get this error intermittently (i.e. sometimes it works).

**Comment by bartekn** [comment]
> Just to throw a wrench into the mix, it seems that when I put horizon behind a load balancer and enable session stickyness, I get this error intermittently (i.e. sometimes it works).

Does it work when you connect to horizon directly (it's not behind a load balancer)? Maybe load balancer has problems connecting your horizon instance (wrong security group, closed IPs, machine's firewall, etc.

**Comment by istrau2** [comment]
@bartekn 

Yes, it works fine when I connect to horizon directly.

Couple of points:

1. The error is intermittent (when sticky sessions are enabled).

2. Even when I get a timeout, the transaction gets submitted to the network (meaning the request got through)

3. All other get methods work just fine.

I guess what I am saying is that I know that my requests are getting to horizon. The only issue is that I sometimes get a timeout response (even when the transaction gets submitted to the network). I don't think its related to security groups/firewall.

**Comment by bartekn** [comment]
What load balancer are you using? ELB? What's the idle timeout value?

**Comment by istrau2** [comment]
@bartekn I am using AWS ELB (Application Load Balancer). Timeout is 60 seconds.

**Comment by istrau2** [comment]
I think I may have found the problem/solution.

@bartekn @jedmccaleb @nullstyle I think it may have been related to security groups after all as @bartekn suggested. It seems I needed to allow my load balanced instances to communicate back with my load balancer (security group wise). For some reason (which I still don't understand), this problem only showed itself for the POST transactions endpoint.

Can anyone confirm that they are able to go to beta.lupoex.com and create a transaction from there?

**Comment by istrau2** [comment]
Never mind, it is still happening intermittently.

**Comment by bartekn** [comment]
Could you upload your horizon and core logs to [gist](https://gist.github.com/) or similar? To login to your docker container:
```
docker exec -it [name] /bin/bash
```
Logs can be found in /var/log/supervisor.

**Comment by istrau2** [comment]
@bartekn Can I email them to you?

**Comment by bartekn** [comment]
They shouldn't contain any private info but if you're concerned, ok you can send a link to gist via Slack PM. I'm `bartek` there.

**Comment by istrau2** [comment]
@bartekn Now that you mention the logs, I have examined both my instances (I am running two instances of horizon).

One seems to have logs like this:
```
time="2017-11-21T16:56:45Z" level=info msg="Finished request" bytes=234 duration=19.987558119s host=xxx ip="xxx" method=POST path="/transactions" pid=21 req="2b22a43e7902/7oIvTT7Bmi-001602" status=504 streaming=false
```

while the other seems to have logs like this:
```
time="2017-11-21T16:56:18Z" level=info msg="Finished request" bytes=2280 duration=3.558592451s host=xxx ip="xxx" method=POST path="/transactions" pid=19 req="6f01253cee7a/o1HeE7J8wL-002472" status=200 streaming=false
```

**Comment by istrau2** [comment]
@bartekn 

Alright, I have some more news. It seems, that the timeout issue is related to that specific horizon instance. If I connect to directly to that instance locally without any load balancer in the middle and try to submit a transaction, I get the 504.

**Comment by istrau2** [comment]
@bartekn @nullstyle @jedmccaleb Well, I moved the horizon instance to a new availability zone / subnet in AWS and it seems to now be working. I have no explanation for it. I checked everything I could think of regarding the subnet that wasn't working and could't find a reasonable explanation. I guess you can close this. Sorry I don't have more info.
