### ISSUE TITLE
Order Book endpoint : order_limit incorrect

### ISSUE THREAD

**Issue by gouth7** [stellar/go-horizon#372]
When horizon is provided an order_limit of 0, it returns the default quantity of 10. In this scenario, it should probably return nothing. 

https://horizon-testnet.stellar.org/order_book/trades?limit=0&order=asc

Furthermore, negative order_limit values return internal server error's.

**Comment by nullstyle** [comment]
Diagnosis:  `db2.GetPageQuery` interprets an input limit of `0` as "Please use your default page size" and `actions.GetPagingParams` does not properly scrub input values before passing on to `GetPageQuery`

Solution:  return an error when a limit of `0` is explicitly specified, returning an invalid limit error response.  Implement regression test.

Thanks @gouth7 for the catch!
