### ISSUE TITLE
links in horizon output are incorrect

### ISSUE THREAD

**Issue by gouth7** [stellar/go-horizon#377]
In horizon, the /order_book/trades endpoint shows incorrect links. 

EX. At the following link, the issue below exists. 
 
https://horizon.stellar.org/order_book/trades?selling_asset_type=native&buying_asset_type=credit_alphanum4&buying_asset_code=CNY&buying_asset_issuer=GAREELUB43IRHWEASCFBLKHURCGMHE5IF6XSE7EXDLACYHGRHM43RFOX&limit=200&order=desc

**Now:**
["_links"]["next"]["href"] = "https://horizon.stellar.org/order_book/trades?order=desc\u0026limit=200\u0026cursor=53009169267036161-1"

**Should be:**
["_links"]["next"]["href"] = "https://horizon.stellar.org/order_book/trades?order=desc&limit=200&cursor=53009169267036161-1"

'\u0026' should be replaced with '&'

same for ["_links"]["self"]["href"] and ["_links"]["prev"]["href"]

**Comment by bartekn** [comment]
Duplicate https://github.com/stellar/horizon/issues/113
