### ISSUE TITLE
Horizon hangs

### ISSUE THREAD

**Issue by pitersky** [stellar/go-horizon#387]
Hi

We are experiencing some hangs issues with our horizon and stellar-core instances. Horizon is buit from git with tag 0.11.0 (but the same was with previous release too). Core version is 0.6.3. Current answer from horizon is 

```
  "horizon_version": "",
  "core_version": "v0.6.3-4-g708237b",
  "history_latest_ledger": 13093894,
  "history_elder_ledger": 13089664,
  "core_latest_ledger": 13094346,
  "core_elder_ledger": 13089664,
```

core_latest_ledger is synced with the network. history_latest_ledger at some time stops syncing. Resync of horizon db didn't help, only deleting of stellar-core and horizons db works. In stellar-core there are no error messages, in horizon there is 
```
Aug 23 14:15:25 horizon[23092]: time="2017-08-23T14:15:25Z" level=error msg="ledger gap detected (possible db corruption): validateLedgerChain: failed to load cur leedger gap detected (possible db corruption): validateLedgerChain: failed to load cur ledger: sql: no rows in result set" pid=23092 start=13093895
```
This error spawns a lot.

We tried Correcting gaps in historical data from here ```https://github.com/stellar/horizon/blob/master/docs/reference/admin.md``` but it didn't helps. Looking for any help and advices.

**Comment by nullstyle** [comment]
@pitersky you need to have your stellar-core configured to use the `CATCHUP_RECENT` feature to avoid gaps in history.  You can see an example here:  https://github.com/stellar/docker-stellar-core-horizon/blob/master/pubnet/core/etc/stellar-core.cfg#L7  (our docker images can tolerate being out of sync for 60480 ledgers without the need for administrator interference)

By default, stellar-core will only run minimal catchup, which will not fully populate the `txhistory` table will transactions that happened during the period your stellar-core was out of sync.  If this table is not fully populated, horizon cannot properly ingest the network history.
