### ISSUE TITLE
Unexpected effect from setting inflation

### ISSUE THREAD

**Issue by istrau2** [stellar/go-horizon#390]
It seems that setting the inflation destination on an account produces a SIGNER UPDATED effect. I found that quite unexpected (and frightening).

**Comment by vogel** [comment]
Do you have ledger number and operation number for that inflation?

**Comment by vogel** [comment]
Seems like horizon cannot handle inflation dest or not-changing-signers in set_options at all:

https://github.com/stellar/horizon/blob/ee87b148ed34156fedcbca52a2155019e7606689/src/github.com/stellar/horizon/ingest/session.go#L399

**Comment by jedmccaleb** [comment]
I just wanted you to confirm it isn't a core issue

**Comment by vogel** [comment]
It is not a core issue - horizon reports all not-removed signers as updated on every set_option operation. And there is no code to report changing the inflation destination.

**Comment by nullstyle** [comment]
this is something I'll look into fixing today
