### ISSUE TITLE
Client generated offer id

### ISSUE THREAD

**Issue by s-a-y** [stellar/go-horizon#391]
Not sure if it belongs here or in stellar-core repo.
Is it possible to return offer id from Manage offer operation? If not, is it possible to allow client generated uuid as offer id?
It's currently quite hard to trade using horizon endpoints.

**Comment by poliha** [comment]
An offer Id is returned from Manage Offer. It is in the result_xdr string. 
Try making a manage offer operation in stellar lab and review the result_xdr string.

**Comment by nullstyle** [comment]
@s-a-y Could you please provide better details as to what specifically you're trying to achieve and why the current API makes that hard.  I need to understand your problem better to figure a solution.

**Comment by s-a-y** [comment]
@poliha thanks, I'm stupid, I haven't actually checked result_xdr.
That solves it for me for now.
@nullstyle I'm not there yet, but I thought client generated ids might be useful in case you have many users trading, then submitting their transactions will go through the queue and channels and then you don't need to build feedback loop to communicate back offer id, because client already knows it

**Comment by nullstyle** [comment]
I'm going to close this for now until we have a better specified use case to work against
