### ISSUE TITLE
Ability to return more orders of a given order book

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/go-horizon#399]
Right now it only returns 10 orders on each side. I think it should be configurable by the horizon operator or maybe make it where you can page through the orders on each side.

**Comment by jedmccaleb** [comment]
Quick fix here is to just make the limit configurable until we can design a more robust solution with paging.

**Comment by nullstyle** [comment]
https://github.com/stellar/horizon/blob/master/src/github.com/stellar/horizon/db2/core/order_book_summary.go#L68
