### ISSUE TITLE
streaming query to /ledgers has problems

### ISSUE THREAD

**Issue by thejollyrogers** [stellar/go-horizon#4]
- When I connect to this endpoint, it returns the first 10 transactions and then my onerror callback gets called.
- the "after" parameter doesn't seem to be respected

**Comment by thejollyrogers** [comment]
@nullstyle

**Comment by thejollyrogers** [comment]
To further expound:

GET /ledgers?limit=1&after=2
response:
{"_links":{"effects":{"href":"/ledgers/1/effects{?after}{?limit}{?order}","templated":true},"operations":{"href":"/ledgers/1/operations{?after}{?limit}{?order}","templated":true},"self":{"href":"/ledgers/1"},"transactions":{"href":"/ledgers/1/transactions{?after}{?limit}{?order}","templated":true}},"id":"43cf4db3741a7d6c2322e7b646320ce9d7b099a0b3501734dcf70e74a8a4e637","hash":"43cf4db3741a7d6c2322e7b646320ce9d7b099a0b3501734dcf70e74a8a4e637","prev_hash":"","sequence":1,"transaction_count":0,"operation_count":0,"closed_at":"0001-01-01T00:00:00Z"}
ERROR! <-- onerror callback called
{ type: 'error' } <-- the EventSource error object

**Comment by nullstyle** [comment]
After investigating, we do not have an easy way to properly avoid triggering the `onerror` callback of an eventsource object when closing the connection server side.  To make issues worse, the `onerror` callback provides basically no info about the underlying error.

As such, your application should ignore the `onerror` callback, and instead listen for messages on the `err` channel (i.e. `event: err` in SSE terms).

The point of the above:  this is not a behavior we can change, and it will continue to behave this way.

---

In testing, it is safe to ignore the `onerror` callback.  The event source object itself will simply open up another connection and try again, as you would expect.
