### ISSUE TITLE
operations end point or stream return offer_id: 0 when create passive offer

### ISSUE THREAD

**Issue by datspider** [stellar/go-horizon#404]
{
"id": "1735093773144065",
  "paging_token": "1735093773144065",
  "source_account": "GC2LDGP3TK24PBWMMZWFGMXBHZ64KITJN7S6TXE6YWIV2E6SKSYHQOB4",
  "type": "create_passive_offer",
  "type_i": 4,
  "offer_id": 0,
  "amount": "600.0000000",
  "price": "0.5000000",
  "price_r": {
    "n": 5000000,
    "d": 10000000
  },
  "buying_asset_type": "credit_alphanum4",
  "buying_asset_code": "AOA",
  "buying_asset_issuer": "GBHC3K3ABXRBVKWZVIYW3AEGDFGW46VUUJYVQUR26SNK2GHVOT6MMXRG",
  "selling_asset_type": "credit_alphanum4",
  "selling_asset_code": "AMD",
  "selling_asset_issuer": "GARQZGMFOG63YM3TW54OAZEPSHEYWIYJI34VAMZ47Q2SPJ7EVMBV6IBX"
}
All passive offer data I try to query return offer_id: 0

**Comment by jedmccaleb** [comment]
offer_id shouldn't be there
