### ISSUE TITLE
Consider decreasing testnet friendbot payout

### ISSUE THREAD

**Issue by bartekn** [stellar/go-horizon#405]
Someone is draining testnet friendbot (7M in the last 24h). At this rate there will be no more testnet lumens in a few months. Seems like an easier option than using catpcha etc.

**Comment by nullstyle** [comment]
This is why we can't have nice things.

**Comment by nullstyle** [comment]
Also, @bartekn please include the evidence you've collected about the drainer.  We should come up with the potential solutions as a group as opposed to just considering one solution free from context.

**Comment by jedmccaleb** [comment]
Also resetting testnet every few months doesn't seem terrible

**Comment by nikhilsaraf** [comment]
we could consider rate-limiting new account creation requests to the friendbot by ip address

**Comment by nullstyle** [comment]
@nikhilsaraf I could see us implementing more aggressive rate limiting than our usual limit for this endpoint, but I would be concerned about the engineering cost given the severity of this problem (low).  Friendbot is only used on testnet and we tolerate a bit of bumpiness in maintaining testnet, given that we run pre-release code on it and may reset it at any time.

---

I'd like to identify, if we can, whether the actor draining friendbot appears like someone being a dick or someone who just left a runaway script running. We've seen situations in the past where a partner left a test script in an infinite loop for days.  A malicious actor could presumably route through TOR and easily sidestep our rate limiting. Any info you've got to inform the question "Is this a bad actor or a runaway script?" would be much appreciated @bartekn

**Comment by bartekn** [comment]
> Also, @bartekn please include the evidence you've collected about the drainer. We should come up with the potential solutions as a group as opposed to just considering one solution free from context.

Yeap, when I created this issue I just noticed the problem and proposed an easiest solution as there are more important things to do.

> Also resetting testnet every few months doesn't seem terrible

Yes, haven't thought of this.

> I'd like to identify, if we can, whether the actor draining friendbot appears like someone being a dick or someone who just left a runaway script running. We've seen situations in the past where a partner left a test script in an infinite loop for days. A malicious actor could presumably route through TOR and easily sidestep our rate limiting. Any info you've got to inform the question "Is this a bad actor or a runaway script?" would be much appreciated @bartekn

I glanced through logs and it looks like these requests are coming from a set of IPs so rate limiting wouldn't help here. Unfortunately, because of the fact that horizon sends `ip` field with port (like `ip:port`) it's hard to aggregate this field.

I guess we can leave the payout as it is if reseting testnet is not a lengthy process.
