### ISSUE TITLE
Cannot estimate paths when account has many trustlines

### ISSUE THREAD

**Issue by s-a-y** [stellar/go-horizon#409]
I'm trying to find paths from BTC to XLM
[Here's the query](https://horizon.stellar.org/paths?source_account=GBR3RS2Z277FER476OFHFXQJRKYSQX4Z7XNWO65AN3QPRUANUASANG3L&destination_account=GBR3RS2Z277FER476OFHFXQJRKYSQX4Z7XNWO65AN3QPRUANUASANG3L&destination_asset_type=native&destination_amount=1000)

I'll post example result here, because it changes over time
```
{
"_embedded": {
"records": [
{
"source_asset_type": "native",
"source_amount": "1000.0000000",
"destination_asset_type": "native",
"destination_amount": "1000.0000000",
"path": []
},
{
"source_asset_type": "credit_alphanum4",
"source_asset_code": "ICN",
"source_asset_issuer": "GBDEVU63Y6NTHJQQZIKVTC23NWLQVP3WJ2RI2OTSJTNYOIGICST6DUXR",
"source_amount": "11.9476800",
"destination_asset_type": "native",
"destination_amount": "1000.0000000",
"path": []
},
{
"source_asset_type": "credit_alphanum4",
"source_asset_code": "LTC",
"source_asset_issuer": "GC5LOR3BK6KIOK7GKAUD5EGHQCMFOGHJTC7I3ELB66PTDFXORC2VM5LP",
"source_amount": "0.3664700",
"destination_asset_type": "native",
"destination_amount": "1000.0000000",
"path": []
},
{
"source_asset_type": "credit_alphanum4",
"source_asset_code": "BAT",
"source_asset_issuer": "GBDEVU63Y6NTHJQQZIKVTC23NWLQVP3WJ2RI2OTSJTNYOIGICST6DUXR",
"source_amount": "103.8522300",
"destination_asset_type": "native",
"destination_amount": "1000.0000000",
"path": []
},
{
"source_asset_type": "credit_alphanum4",
"source_asset_code": "REP",
"source_asset_issuer": "GBDEVU63Y6NTHJQQZIKVTC23NWLQVP3WJ2RI2OTSJTNYOIGICST6DUXR",
"source_amount": "1.0196900",
"destination_asset_type": "native",
"destination_amount": "1000.0000000",
"path": []
}
]
}
}
```

[Horizon limits number of returned paths to 5](https://github.com/stellar/horizon/blob/b21091bb68cd9ae0b2643a5cf00b743a48f65c17/src/github.com/stellar/horizon/simplepath/search.go#L82)
and since I have many trust lines there is a good chance that BTC won't be present in the result set.

Increasing or making limit a parameter is dangerous for performance, so I assume `sourceAsset` optional parameter is required to be able to estimate paths between assets of my choice.

**Comment by jedmccaleb** [comment]
look at potential design to fix this

**Comment by nikhilsaraf** [comment]
After looking into this.. we are currently getting all the assets available to the source account as inputs to the pathfinder query (takes in an array of source assets). We can very easily limit this to a single source asset based on new optional url params. This will also be backwards compatible.

**Comment by jedmccaleb** [comment]
how expensive is it to raise the limit to say 20?

**Comment by s-a-y** [comment]
I imagine I'll have more than 20 tokens anyway, so either there should be a way to specify, or I'll be using some dummy accounts with few trustlines each (doesn't require anything from your side)

**Comment by jedmccaleb** [comment]
specifying seems weird to me since I'm not sure how the user would know what to specify? I think we need paging ultimately

**Comment by s-a-y** [comment]
User may not know, but wallet knows what assets user has, I don't see a problem to have that as an option.
Yeah, paging is an option, but I guess having paging I'd still try to avoid it in my implementation, sending 3 consequent requests introduces big delay
