### ISSUE TITLE
When running --newdb end with a successful message

### ISSUE THREAD

**Issue by zachvanduyn** [stellar/go-horizon#410]
I think the last thing printed to stdout is something like: "Application destroyed"

Maybe we can put a success message in there for users?

**Comment by bartekn** [comment]
"Application destroyed" looks like a message from stellar-core.

**Comment by zachvanduyn** [comment]
Got it, should I create another ticket and destroy this one?

**Comment by bartekn** [comment]
Yes, you should move this to stellar-core repo.
