### ISSUE TITLE
Use flat file instead of environment variables

### ISSUE THREAD

**Issue by zachvanduyn** [stellar/go-horizon#411]
Instead of sourcing a file like:

`export DATABASE_URL="postgresql://localhost/horizon?user=horizon_user_name&password=horizon_new_password"`
`export STELLAR_CORE_DATABASE_URL="postgresql://localhost/core?user=core_user_name&password=core_new_password"`
`export STELLAR_CORE_URL="http://127.0.0.1:11626"`
`export PER_HOUR_RATE_LIMIT=72000`
`export LOG_LEVEL="debug"`
`export INGEST="true"`

Can we just use a flat .cfg file like stellar-core.cfg?

**Comment by bartekn** [comment]
Duplicate https://github.com/stellar/stellar-horizon/issues/63
