### ISSUE TITLE
New User - XLM and Centaurus app  - need help withdrawing. WTF

### ISSUE THREAD

**Issue by balibaby** [stellar/go-horizon#412]
Hello,

I have recently purchased 30k lumens and I have stored them on the "Centaurus" App for Android.  I'm having significant withdrawal issues and am asking for assistance as soon as possible. 

I have submitted a withdrawal 3 HOURS AGO to bittrex and my stellar wallet shows the transaction as pending in the Centaurus app, but NOTHING on bittrex.

I have sent a small amount of stellar to kraken, and the centaurus app shows pending, and kraken shown nothing even pending.

I try to send stellar to my xlm wallet and it says "tx_failed, op_low_reserve". This app is very user-unfriendly and doesn't give any instructions or anything.  

Please help me as I want to trade this as soon as possible.

**Comment by bartekn** [comment]
Please create a new issue in Centaurus repo: https://github.com/TbLtzk/Centaurus and also copy your Stellar public key there.
