### ISSUE TITLE
SSE Stream closing without terminating chunk...

### ISSUE THREAD

**Issue by elucidsoft** [stellar/go-horizon#414]
The SSE Stream is closing without issuing the terminating chunk, this is causing all sorts of issues.  You can reproduce this behavior by issuing the following command:

`curl --header "Accept: text/event-stream" https://horizon-testnet.stellar.org/accounts/GAZHWW2NBPDVJ6PEEOZ2X43QV5JUDYS3XN4OWOTBR6WUACTUML2CCJLI/transactions?limit=50`

It downloads the data and then fails at the end with the error:

`curl: (18) transfer closed with outstanding read data remaining`

I have also been able to reproduce this issue in .NET HttpClient, and Fiddler both stating that the chunk did not terminate properly.  Since this behavior violates RFC specification for chunk many clients will be unable to use the SSE Streams with Horizon.

**Comment by bartekn** [comment]
Let's discuss in https://github.com/stellar/go/issues/154
