### ISSUE TITLE
Follow Received Payments tutorial examples is out of date

### ISSUE THREAD

**Issue by oryband** [stellar/go-horizon#418]
There are multiple sections that either don't comply with the latest SDK or randomly don't work with missing information:

# Issue 1

```bash
$ curl "https://horizon-testnet.stellar.org/friendbot?addr=GB7JFK56QXQ4DVJRNPDBXABNG3IVKIXWWJJRJICHRU22Z5R5PI65GAK3"
```
This randomly fails with wither `"bad sequence"` or `"op_underfunded"`, might be related to #405.

# Issue 2

`make_payment.js` has some out of date code.

## addSigner() not in SDK

This is possibly related to stellar/js-stellar-base/issues/46:

```javascript
var transaction = new StellarBase.TransactionBuilder(account)
  .addOperation(StellarBase.Operation.payment({
    destination: StellarBase.Keypair.random().publicKey(),
    asset: asset,
    amount: amount
  }))
  .addSigner(keypair)  // This function has been removed from the SDK.
  .build();
```

Instead, the mentioned line should be removed and this one should be added instead after the above statement:

```javascript
transaction.sign(keypair);
```

## Network is missing

Also, the network should be set to testnet at the head of the file:

```javascript
StellarBase.Network.useTestNetwork();
```

## Inconsistent sequence number

Furthermore, you should probably fetch the latest sequence number automatically instead of forcing the person following the tutorial to copy+paste it from a previous output in the tutorial. This might help to avoid requesting with an invalid number.

**Comment by lbeder** [comment]
👍

**Comment by bartekn** [comment]
Issue 1 is tracked in: https://github.com/stellar/go/issues/134
Issue 2 fixed in: https://github.com/stellar/go/pull/234

We're also working on testing our examples so once it's done we will fix the issues faster. Thanks!
