### ISSUE TITLE
SSE Streams only stay open for 1 minute

### ISSUE THREAD

**Issue by jackkleeman** [stellar/go-horizon#424]
As far as I can tell, SSE streams from the public stellar horizon servers close (with an EOF) after 1 minute. If you run a bridge connected to these servers you will see `Started listening for new payments ` logged every minute, which really pollutes server logs!

**Comment by bartekn** [comment]
It's happening because horizon.stellar.org is behind Elastic Load Balancer which kills idle connections after one minute. You can deploy your own horizon server and it shouldn't be happening.

**Comment by jackkleeman** [comment]
Could we implement a heartbeat?

**Comment by bolshoy** [comment]
@bartekn see https://aws.amazon.com/blogs/aws/elb-idle-timeout-control/ 
I would recommend setting it to maximum - 3600 seconds.

One possible downside of a short timeout - with request retry implementation that does not take into account the cursor (or last_id in sse), the code can retry each minute with the same cursor, and read the same data over and over.

@jackkleeman exactly, looking at the https://www.w3.org/TR/eventsource/:
>Legacy proxy servers are known to, in certain cases, drop HTTP connections after a short timeout. 
>To protect against such proxy servers, authors can include a comment line 
>(one starting with a ':' character) every 15 seconds or so.

**Comment by bartekn** [comment]
OK, let's discuss here: https://github.com/stellar/go/issues/376
