### ISSUE TITLE
Friendbot intermittently failing to fund account.

### ISSUE THREAD

**Issue by Synesso** [stellar/go-horizon#427]
I’m getting bad_tx_seq errors intermittently using friendbot.

It’s pretty consistent at this time. I saw it once in the lab, but clicked the button again and it worked. 

But a few of my builds have failed in a row. e.g. https://travis-ci.org/Synesso/scala-stellar-sdk/builds/342235034#L817

**Comment by bartekn** [comment]
It was happening because of an error in deployment process of one of our services. Should work correctly now.

**Comment by gurugeek** [comment]
still fails now using the nodejs sdk .. 
ERROR! { type: 'https://stellar.org/horizon-errors/https://stellar.org/horizon-errors/transaction_failed',
  title: 'Transaction Failed',
  status: 400,
  detail: 'The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains further details.  Descriptions of each code can be found at: https://www.stellar.org/developers/learn/concepts/list-of-operations.html',

**Comment by bartekn** [comment]
OK, we switched to a new friendbot service and there are some problems with deployment. I created this account with 10M testnet lumens, please use this until friendbot is fixed. Please respect others: don't send more than you need (especially full balance 😉), if you need more accounts use this one only once and then create accounts from your new account (this is to not use each other seqnums):
```
Public Key    GBW74UVOXKGHO3WX6AV5ZGTB4JYBKCEJOUQAUSI25NRO3PKY5BC7WYZS
Secret Key    SA3W53XXG64ITFFIYQSBIJDG26LMXYRIMEVMNQMFAQJOYCZACCYBA34L
```

**Comment by gurugeek** [comment]
thanks a lot 👍 much appreciated..will only use to send small amounts for testing purposes of course :)

**Comment by gurugeek** [comment]
umh @bartekn from stellar lab also payments in the test network seems to fail

{
  "type": "https://stellar.org/horizon-errors/transaction_failed",
  "title": "Transaction Failed",
  "status": 400,
  "detail": "The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains further details.  Descriptions of each code can be found at: https://www.stellar.org/developers/learn/concepts/list-of-operations.html",
  "extras": {
    "envelope_xdr": "AAAAAG3+Uq66jHdu1/Ar3Jph4nAVCIl1IApJGuti7b1Y6EX7AAAAZABzN+EAAAA2AAAAAAAAAAAAAAABAAAAAAAAAAEAAAAALCZvfp2D7Zrn7uv96tgisRnBDJjxaJEoMuJSosOzmZYAAAAAAAAAF0h26AAAAAAAAAAAAVjoRfsAAABAjeDEMZS/IrDxtz30VxVwmUH9rsAe39cZuNLFgORCH0OnKebUTg0Hyexjh2i3Te4n5zK5igpyrGQlqC5v/PRXCQ==",
    "result_codes": {
      "transaction": "tx_failed",
      "operations": [
        "op_no_destination"
      ]
    },
    "result_xdr": "AAAAAAAAAGT/////AAAAAQAAAAAAAAAB////+wAAAAA="
  }

**Comment by bartekn** [comment]
You have to use [`create_account`](https://www.stellar.org/developers/guides/concepts/list-of-operations.html#create-account) operation.

**Comment by gurugeek** [comment]
@bartekn my bad, thanks again !!

**Comment by gurugeek** [comment]
Sorry for reopening this but apparently this code
```

var request = require('request');
request.get({
  url: 'https://horizon-testnet.stellar.org/friendbot',
  qs: { addr: pair.publicKey() },
  json: true
}, function(error, response, body) {
  if (error || response.statusCode !== 200) {
    console.error('ERROR!', error || body);
  }
  else {
    console.log('SUCCESS! You have a new account :)\n', body);
  }
});
```

from the example at https://www.stellar.org/developers/guides/get-started/create-account.html still fails. I have noticed that in stellar lab Friendbot works fine now so I am wondering if the api/example changed recently?

Error 
title: 'Transaction Failed',
  status: 400,
  detail: 'The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains further details.  Descriptions of each code can be found at: https://www.stellar.org/developers/learn/concepts/list-of-operations.html',
  extras: 
   { envelope_xdr: 'AAAAABB90WssODNIgi6BHveqzxTRmIpvAFRyVNM+Hm2GVuCcAAAAZABiwhcAAIcyAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAALMt7Y8euYoMuziWEiGDzyf9HSnuC7WFJk4glGUbftXwAAAAXSHboAAAAAAAAAAABhlbgnAAAAED69gVZaoZyDWLq2XhN0kTs6/nTVzUfhjV2lgXMoMwZZxRzMshXdgZHDPKaT8AVXyXr9zv5s4CNtoMMjoqo/ekK',
     result_codes: { transaction: 'tx_failed', operations: [Array] },
     result_xdr: 'AAAAAAAAAGT/////AAAAAQAAAAAAAAAA/////AAAAAA=' } }
Doctors-MacBook-Pro:stellarjs doctorstrange$

**Comment by bartekn** [comment]
Unfortunately there are still problems connected to Friendbot, we have a fix ready in https://github.com/stellar/go/pull/330. Right now you have to use the solution here: https://github.com/stellar/horizon/issues/427#issuecomment-368336973.

**Comment by gurugeek** [comment]
okay @bartekn using it for 25 lumen peer new account so shouldn't be too much :)

**Comment by ckmakcesar** [comment]
@bartekn i notice that the friendbot flag for horizon has changed from "--friendbot-secret" (v0.11) to --friendbot-url" (v0.12prebuilt / version "devel"), which might have caused the matter. Is it better to stay with v0.11 for the moment? 

Thanks man

**Comment by Synesso** [comment]
Friendbot is now reporting success, but silently failing. 

https://stellar.stackexchange.com/questions/712/funded-account-nothing-showing-up-on-testnet-explorer

I have confirmed the behaviour just now via Laboratory

**Comment by gastzars** [comment]
still can not get it works here

**Comment by nelsou** [comment]
The friendbot you gave has no balance left. I use this one instead
```
Public Key    GBW74UVOXKGHO3WX6AV5ZGTB4JYBKCEJOUQAUSI25NRO3PKY5BC7WYZS
Secret Key    SA3W53XXG64ITFFIYQSBIJDG26LMXYRIMEVMNQMFAQJOYCZACCYBA34L
```

**Comment by mbiqbal** [comment]
Maybe this will save someone some time. The url is now https://friendbot.stellar.org?addr=<ADDRESS>
I don't know why or how. Saw it on stellar lab.

**Comment by bartekn** [comment]
I believe this is now solved. Docs has been updated with a correct URL.
