### ISSUE TITLE
Is Test Network down?

### ISSUE THREAD

**Issue by githubr** [stellar/go-horizon#429]
I tried to create a new account and fund it on Test Network through:
https://www.stellar.org/laboratory/#account-creator?network=test

But I got the following message:

```
    {
      "type": "https://stellar.org/horizon-errors/https://stellar.org/horizon-errors/transaction_failed",
      "title": "Transaction Failed",
      "status": 400,
      "detail": "The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains further details.  Descriptions of each code can be found at: https://www.stellar.org/developers/learn/concepts/list-of-operations.html",
      "extras": {
        "envelope_xdr": "AAAAABB90WssODNIgi6BHveqzxTRmIpvAFRyVNM+Hm2GVuCcAAAAZABiwhcAAH4yAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAA8KPV2NXmxeVEg7Y2Wi64GQo5ua5YGFfT5QWo6It69m8AAAAXSHboAAAAAAAAAAABhlbgnAAAAEAB4Hl/em5wUGSg2kVItCOK7p5Nh5pydlCchDfnQCxEne2X43NUl+nyM1G7eCWCcbhZClVvWVIdoMTFUy3lRA0G",
        "result_codes": {
          "transaction": "tx_bad_seq"
        },
        "result_xdr": "AAAAAAAAAAD////7AAAAAA=="
      }
    }
```

**Comment by atla** [comment]
Hey, we are currently at a Hackathon and wanted to use stellar testnetwork as well,  we are running into the same issue with all tests we tried (java, go, JS)

**Comment by bartekn** [comment]
Yes, there is a problem with friendbot. Please send me your public keys and I will send some testnet lumens.

**Comment by atla** [comment]
Hey @bartekn thanks for the offer, if possible could you fund these few testnet accounts as we would need several addresses to build our hackathon showcase:

1. GC7JELXPLI6OLYUKAOAKCTNDWY75WTUUYCKJO4SG4CH3762FICMOVHQK
2. GDCPIJ44NH3LLUBCSAHNG37JVWAXX3KD4UEXRLOH6W7RG2FQMPMDVKFE
3. GDNGETDRCEPHQYGSUPMDEUXV7CMHV5L5BD3Z6OEMNBSELRKMQTNNG6AX
4. GBHVT6Y6FAL63CCA5M2TUZLYZKQ2GWIWNLBKD5BKMOZLXLRYZDM5ZNDG
5. GDVQTUBNZAHEVNBTDGGJOUWKDQJRRD342VMFYIV6IBLSDDUDTRE6KQDA
6. GBP6L622HVSEQ2HXR6DZHQRBDGSADX4ED3O5YTBW3NK4QVXDIDDYRMST
7. GBRP2K3V2GEZA6V2T4CAC5G2FIFN7372EF5VFF5OZZXMCYMYLRMNV4V4
8. GCNCOCYJAH3WHNGRRSAEHBFDA7RTH5G6YBOR4A5CIJDWO5DMCUJV76CS
9. GCKDC6RD5M7WK7TYLK2HWZVYLGHY6SFYWJMJTBZQ7N66J7DFUK4UVNPL
10. GDXMIJ3OCLAXKAZZ37MZ4RM6NL3PEK4QKE3QAMHF46DML6PMHV3BEHIT

Ideally we wanted to create them on demand but it should be enough if we can use several different addresses for client and server.

edit:

Do you know when the friendbot would be up&running again? Is this only temporarily or should we expect it to be gone during the whole weekend?

**Comment by bartekn** [comment]
It should be fixed in a few hours at max. OK sent 100,000 testnet XLM to GC7JELXPLI6OLYUKAOAKCTNDWY75WTUUYCKJO4SG4CH3762FICMOVHQK.

**Comment by atla** [comment]
Thanks a lot, we are currently trying to fund the other accounts with that amount!

**Comment by bartekn** [comment]
This issue should now be resolved.

**Comment by githubr** [comment]
Thanks ... yep I have been able to send some test lumens.
