### ISSUE TITLE
Decode Managed Data values on the Accounts endpoint

### ISSUE THREAD

**Issue by MikeFair** [stellar/go-horizon#441]
Currently when you load an account, the values are still base64 encoded.
like this:
```
    "value1": "Mjc3YWNkN2EtN2Y5NS00ZDNhLWIzZmUtYzE0YTQwMjU0OThj",
    "value2": "aHR0cHM6Ly9zdGVsbGFyd2F0Y2guZnBlbnQubmV0L3N0ZWxsYXIvd2ViaG9va3MvcGF5bWVudA==",
    "value3": "MjA0NzZlZWEtNTMwNS00ZDYwLTg0NWMtOGVhNGVhODJiMDc5"
```
It seems there is a function "Raw()" that is supposed to decode these values, but it is not called.

I noticed the functions are directly returning the sql response without decoding the values first.

**Comment by bartekn** [comment]
This should be decoded client side. For example, in Go SDK you can use [`Account.GetData`](https://godoc.org/github.com/stellar/go/clients/horizon#Account.GetData) method.

**Comment by MikeFair** [comment]
Only the Go SDK has this decoding method.
Should this then become a ticket against the JS SDK for lack of this
function?

On Mon, Mar 26, 2018 at 7:05 AM, Bartek Nowotarski <notifications@github.com

**Comment by bartekn** [comment]
Yes, please create a new issue for this in JS SDK.
