### ISSUE TITLE
run_tests asks for password

### ISSUE THREAD

**Issue by FredericHeem** [stellar/go-horizon#49]
Running _scripts/run_tests.bash_ asks for a password, is it intended ?

**Comment by nullstyle** [comment]
@FredericHeem what happens when you run `gb test github.com/stellar/go-horizon` on the command line?

run_tests.bash should not be asking for a password.  Do you by any chance have `gb` aliased to something in your shell?  for example, I believe that the git plugin for oh-my-zsh defines one.   We can find out for sure if you would run `which gb` and paste the output here.

**Comment by FredericHeem** [comment]
The password is related to postgresql, isn't it ? 

```
frederic@frederic-VirtualBox:~/go-horizon$ which gb
/home/frederic/gocode/bin/gb


frederic@frederic-VirtualBox:~/go-horizon$ gb test github.com/stellar/go-horizon/
Password: 
2015/07/22 08:24:58 exit status 2
E
Errors:

  * /home/frederic/go-horizon/src/github.com/stellar/go-horizon/actions_account_test.go 
  Line 14: - exit status 2 
  goroutine 9 [running]:
  log.Panic(0x1895dca8, 0x1, 0x1)
    /usr/local/go/src/log/log.go:307 +0x9b
  github.com/stellar/go-horizon/test.loadSqlFile(0x84f3148, 0x36, 0x1896e860, 0x1a)
    /home/frederic/go-horizon/src/github.com/stellar/go-horizon/test/main.go:87 +0x2c7
  github.com/stellar/go-horizon/test.LoadScenario(0x84589f8, 0x4)
```

**Comment by nullstyle** [comment]
ah!  I'll add some additional notes into the readme... the test suite assumes that either you override a couple of environment variables to customize database connectivity or that the defaults will connect without need for a password.

``` bash
DATABASE_URL = "postgres://localhost:5432/horizon_test?sslmode=disable"
STELLAR_CORE_DATABASE_URL = "postgres://localhost:5432/stellar-core_test?sslmode=disable"
```

are the effective defaults, and if you cannot run `psql postgres://localhost:5432/horizon_test?sslmode=disable` and get a connection, then the test suite will fail this way.  I'll get that fixed prior to launch.

**Comment by nullstyle** [comment]
Horizon no longer uses the command line psql client during the test run.  This issue should on longer occur.
