### ISSUE TITLE
wrong selling asset_code when getting the offers

### ISSUE THREAD

**Issue by FredericHeem** [stellar/go-horizon#60]

**Comment by FredericHeem** [comment]
fix in PR https://github.com/stellar/go-horizon/pull/57

**Comment by nullstyle** [comment]
@FredericHeem Can you check this against the latest master?  I don't understand the the specific problem from your title alone.

**Comment by FredericHeem** [comment]
Your PR also fixes the issue.
FYI: https://github.com/FredericHeem/go-horizon/commit/2ac9b8d74b8229c835786ec2438c377fc51e7193

**Comment by nullstyle** [comment]
Thanks!
