### ISSUE TITLE
orderbook 404

### ISSUE THREAD

**Issue by FredericHeem** [stellar/go-horizon#66]
Getting the orderbook via the REST API _/orderbooks_ is stil not working, a 404 is returned.

**Comment by nullstyle** [comment]
Fixed in https://github.com/stellar/go-horizon/pull/74

**Comment by FredericHeem** [comment]
Is the rest api  _orderbook_, _orderbooks_ or _order_book_ ?  Please use a consistent naming.

**Comment by nullstyle** [comment]
its `order_book`
