### ISSUE TITLE
Endpoint to determine version of horizon and stellar-core it is talking to

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/go-horizon#73]
"I just took a look at the api and don't see any way to determine what is running on horizon.  I think a good thing to add would be an api feature to determine what version of horizon is running and what steller-core version it is controling"

**Comment by matschaffer** [comment]
Should surface versions for:
- stellar-core
- go-horizon
- ruby-horizion

Could also be good to include information about XDR if we have anything like a version for that. That should make it easier to spot cases where horizon and stellar-core aren't speaking the same language.

**Comment by nullstyle** [comment]
Yeah, good idea.  Let's just add this data to the root resource (which is otherwise just `_links`)
