### ISSUE TITLE
Issues implementing "Trades for orderbook" endpoint

### ISSUE THREAD

**Issue by nullstyle** [stellar/go-horizon#86]
I'm opening this issue to discuss an implementation problem in the open and hopefully enlist some help from the community.  Let me first begin by describing the feature at hand then discuss the possible solutions I see.
## Feature:  Trades for order book API endpoint

This feature will provide a pageable list of all exchanges of value ("trades") that occur between a pair of assets (the "order book").  These trades are created when offers cross (triggered from ManageOffer or CreatePassiveOffer operations) or when an account makes a PathPayment.

Trades don't concretely exist within data model of stellar-core, but having a reified trade within horizon is very useful;  Having it provides a straightforward implementation for any analysis on the history of an order book as well as low-cost interfaces to the distributed exchange provided by the Stellar network.
## Current situation

Presently, trades are stored as a sub-type of "Effect".  Effects are concretely tied to an individual accounts within the Stellar network, with any attributes unique to a  sub-type of effect stored within a jsonb column.  This leads to the current roadblock for implementing the "Trades for orderbook" endpoint:  The information that identifies what order book a trade took place on is in the jsonb "details" column.

We must find a way to efficiently query for trade effects by order book.
## Solution 1: Partial Indexing

By using postgres [partial indexes](http://www.postgresql.org/docs/9.4/static/indexes-partial.html) we could index just the trade effects, ignoring all the other types.  This seems like a pretty clean solution.

Drawbacks:  I don't have an operational experience with partial indexes or jsonb indexes... there may be tricks and traps that we do not realize.
## Solution 2: A new table

For this solution, we would create a new table (probably named "trades") that contains one row per trade and has indexed columns to service the query used to drive the "trades for orderbook" query.

Drawbacks: Storage.  The physical size of the horizon database would grow more quickly as we would be duplicating data and that extra size would be larger than just the size of the extra index as described in solution 1.
## Solution 3:  ???????

What else do we have, any contributions?

---

Personally, I'm leaning towards solution 1, but would love to hear any and all feedback about additional pros/cons of each proposed solution.

**Comment by nullstyle** [comment]
After working through some of the implementation of the trades endpoint, I'm now starting to lean towards solution 2.  Let me explain:

The `history_effects` table records effects upon _an account_ and so operations that cause an interaction between accounts results in duplication at the effects level.  For example, a payment operation results in 2 effects, an account_debited effect for the payer and an account_credited effect for the payee.  

Likewise, a logical trade will end up creating 2 "trade" effects, one from the view point of one party, one from the viewpoint of the other party.

This duplication makes the implementation of a  "All trades" endpoint problematic, as there is no context that allows you to filter out the duplicate records.  The other trading endpoints (Trades by account, Trades by order book) do.

**Comment by nullstyle** [comment]
As a further note:  it's quite possible we could simply not implement the "All trades" endpoint... the utility seems minimal, other than for firehose style data imports for external systems.

**Comment by bartekn** [comment]
In my opinion solution 2 is better too. Since trades data (accounts, amount, assets etc) won't never change a new table seems to be a good idea. What's more we can also think of denormalizing this table so it does not contain no pointers but all trade data (I explained it more in #89).
