### ISSUE TITLE
/accounts/<address>/offers  KO

### ISSUE THREAD

**Issue by FredericHeem** [stellar/go-horizon#98]
The endpoint to get the offers for a given an account is now broken:

```
ERRO[4818] sql: Scan error on column index 11: converting string "0.001" to a int64: strconv.ParseInt: parsing "0.001": invalid syntax  file=src/github.com/stellar/horizon/render/problem/main.go line=71
```

```
stellar=# select * from offers;
                         sellerid                         | offerid | sellingassettype | sellingassetcode |                      sellingissuer                       | buyingassettype | buyingassetcode |                       buyingissuer                       | amount | pricen | priced | price | flags | lastmodified 
----------------------------------------------------------+---------+------------------+------------------+----------------------------------------------------------+-----------------+-----------------+----------------------------------------------------------+--------+--------+--------+-------+-------+--------------
 GAKGBVPUDQAFQWZAUMSOSABSVCF2RYTUMGBNSEN4YPPD3OK5INNC5CYV |       4 |                1 | GBP              | GAGL56EZMYW2NXG3EEU3WGOUKRCL5LDYYPJ3T5FNP4AZ6QPKI532PTXN |               2 | US1234567890    | GAGL56EZMYW2NXG3EEU3WGOUKRCL5LDYYPJ3T5FNP4AZ6QPKI532PTXN |   4000 |      1 |   1000 | 0.001 |     0 |         1299
```

**Comment by nullstyle** [comment]
Looks like the stellar-core guys changed the schema without giving me a heads up.

It'll get fixed momentarily.

Thanks for the report!

**Comment by FredericHeem** [comment]
By the way, do you know how to display the full stacktrace when such a problem occurs ?

**Comment by nullstyle** [comment]
There's not an easy way that I know of... the only solution I've seen is https://github.com/go-errors/errors, which I was planning to integrate (or another such library after I do a survey) at some point in the near future.

I agree, the error messages are just next to useless right now.

**Comment by FredericHeem** [comment]
The new PR still doesn't fix the issue.

**Comment by nullstyle** [comment]
As far as I can tell, it does. this PR has updated the fixture test files to reflect the schema change introduced by stellar-core and `actions_offer_test.go` tests this endpoint in the happy path.

**Comment by nullstyle** [comment]
In addition, I have tested manually before and after this change and have confirmed a failure consistent with the information you provided that is no longer exhibiting itself.  If you're still seeing the bug, please provide a repro.

**Comment by FredericHeem** [comment]
Sorry but I've updated the wrong repo, now go-horizon is horizon...
It now works with your PR, thanks a lot.
